"""
Training data for the topic-category classifier.

Each entry is (text, category) — a forum topic title paired with the
category it belongs to. Assignment was removed as a category: it is a
post TYPE (can be about any subject), not a subject itself, and mixing
it with subject-matter categories was hurting classifier accuracy.
"""

TRAINING_DATA = [
    # SDLC
    ('What is the software development lifecycle?', 'SDLC'),
    ('Can someone explain the phases of SDLC with a real example?', 'SDLC'),
    ('How is the maintenance phase different from the deployment phase?', 'SDLC'),
    ('Why do we need a separate design phase before coding starts?', 'SDLC'),
    ('What happens if you skip the planning phase entirely?', 'SDLC'),
    ('How long should each SDLC phase realistically take for a small project?', 'SDLC'),
    ('Is the SDLC the same thing as a project management framework?', 'SDLC'),
    ('What deliverables come out of the analysis phase?', 'SDLC'),
    ('How do you know when a phase is actually complete?', 'SDLC'),
    ('Which SDLC phase is most often underestimated by new teams?', 'SDLC'),
    ('Does every project need to go through all SDLC phases in order?', 'SDLC'),
    ('What is the difference between the SDLC and the SDLC model chosen for a project?', 'SDLC'),
    ('How do requirements gathering and system design connect in the lifecycle?', 'SDLC'),
    ('Can the testing phase overlap with the implementation phase?', 'SDLC'),
    ('What documentation is expected at the end of each SDLC stage?', 'SDLC'),
    ('Why do some companies add a dedicated feasibility study phase?', 'SDLC'),
    ('How does the lifecycle change for a maintenance-only project?', 'SDLC'),
    ('What is the role of the client during the lifecycle stages?', 'SDLC'),
    ('How do you handle a phase that fails its exit criteria?', 'SDLC'),
    ('Is there a standard number of phases every SDLC must have?', 'SDLC'),
    ('What is the difference between iterative and linear lifecycle models?', 'SDLC'),
    ('How do you retroactively document a project that skipped formal phases?', 'SDLC'),
    ('What is the difference between the SDLC and a software process model?', 'SDLC'),
    ('How do you estimate the timeline for each SDLC phase?', 'SDLC'),
    ('What triggers moving from the design phase into implementation?', 'SDLC'),
    ('How does a spiral model differ from a standard linear SDLC?', 'SDLC'),
    ('What is the purpose of a post-implementation review?', 'SDLC'),
    ('How do you know if a project should skip straight to prototyping?', 'SDLC'),
    ('What risks come from rushing the requirements phase?', 'SDLC'),
    ('How does the V-model pair testing activities with development phases?', 'SDLC'),
    ('What is the difference between system testing and acceptance testing in the lifecycle?', 'SDLC'),
    ('How do you plan for the maintenance phase before the product even ships?', 'SDLC'),
    ('What is a phase gate and why do some teams enforce them strictly?', 'SDLC'),
    ('How do you decide the right SDLC model for a fixed-budget client project?', 'SDLC'),
    ('What happens to the SDLC when a project is cancelled mid-phase?', 'SDLC'),
    ('How does the SDLC differ for embedded systems versus web apps?', 'SDLC'),
    ('What is the cost of fixing a defect found late versus early in the lifecycle?', 'SDLC'),
    ('What is the difference between a functional design and a technical design document?', 'SDLC'),
    ('How do security requirements change the standard phases of the SDLC?', 'SDLC'),
    ('What are the risks of merging the development and testing phases into one continuous loop?', 'SDLC'),
    ('How do you define clear entrance and exit criteria for the implementation phase?', 'SDLC'),
    ('What is the role of a quality assurance lead during the initial planning phase?', 'SDLC'),
    ('How does the lifecycle handle software retirement or decommissioning?', 'SDLC'),
    ('What happens during a post-mortem review at the end of a product release?', 'SDLC'),
    ('Why do some development lifecycles mandate an architectural spike before implementation?', 'SDLC'),
    ('How do user feedback loops affect the maintenance phase of a production system?', 'SDLC'),
    ('What is the difference between the stabilization phase and the active development phase?', 'SDLC'),

    # Methodology
    ('Agile vs Waterfall — which is better for small teams?', 'Methodology'),
    ('When would Waterfall actually be the right choice over Agile?', 'Methodology'),
    ('What is the biggest weakness of Scrum for a two-person team?', 'Methodology'),
    ('How does Kanban differ from Scrum in daily practice?', 'Methodology'),
    ('Can you mix Agile and Waterfall on the same project?', 'Methodology'),
    ('What does a typical sprint planning meeting look like?', 'Methodology'),
    ('Why do some teams fail when adopting Agile too quickly?', 'Methodology'),
    ('How do story points actually get estimated in Scrum?', 'Methodology'),
    ('What is the point of a retrospective if nothing changes afterward?', 'Methodology'),
    ('Is Extreme Programming (XP) still used anywhere today?', 'Methodology'),
    ('How do you choose a methodology for a client who wants fixed pricing?', 'Methodology'),
    ('What is the difference between a Scrum Master and a Project Manager?', 'Methodology'),
    ('How often should sprints actually be — one week or two?', 'Methodology'),
    ('Why does Waterfall struggle with changing requirements?', 'Methodology'),
    ("What does 'done' actually mean in a Scrum board column?", 'Methodology'),
    ('How do standups avoid turning into status reports?', 'Methodology'),
    ('Can a solo developer meaningfully follow Scrum at all?', 'Methodology'),
    ('What is the Agile Manifesto actually saying in plain terms?', 'Methodology'),
    ('How do you measure velocity accurately across sprints?', 'Methodology'),
    ('Is Lean the same thing as Agile or something different?', 'Methodology'),
    ("What happens when a sprint's scope changes halfway through?", 'Methodology'),
    ('What is the difference between Scrum and Scrumban?', 'Methodology'),
    ('How do you run a daily standup for a distributed team across time zones?', 'Methodology'),
    ('What is a burndown chart actually telling you?', 'Methodology'),
    ('How does Crystal methodology differ from Scrum?', 'Methodology'),
    ('What is the role of a product owner versus a project manager in Agile?', 'Methodology'),
    ('How do you handle a stakeholder who wants Waterfall-style fixed deadlines in an Agile project?', 'Methodology'),
    ('What is the definition of ready versus the definition of done?', 'Methodology'),
    ('How do you size a backlog item that nobody has estimated before?', 'Methodology'),
    ('What is timeboxing and why does Agile rely on it so heavily?', 'Methodology'),
    ('How does Feature-Driven Development differ from Scrum?', 'Methodology'),
    ('What is the point of a sprint review if stakeholders rarely attend?', 'Methodology'),
    ('How do you keep a Kanban board from growing unlimited work-in-progress?', 'Methodology'),
    ('What is the difference between incremental and iterative development?', 'Methodology'),
    ('How do methodology choices change once a team scales past ten people?', 'Methodology'),
    ('What is the Scaled Agile Framework (SAFe) trying to solve?', 'Methodology'),
    ('What are the main drawbacks of using Scrumban for a rapidly growing team?', 'Methodology'),
    ('How does the concept of a sprint goal prevent scope creep during development?', 'Methodology'),
    ('What is the role of an Agile coach compared to a standard Scrum Master?', 'Methodology'),
    ('How do you manage dependencies between multiple teams working in the same sprint?', 'Methodology'),
    ('Why do some organizations prefer the Lean software development framework over Scrum?', 'Methodology'),
    ('What is the purpose of a cumulative flow diagram in a Kanban workflow?', 'Methodology'),
    ('How does Extreme Programming handle code ownership and architectural decisions?', 'Methodology'),
    ('What is a planning poker session and how does it improve estimation accuracy?', 'Methodology'),
    ('How do you handle a team member who refuses to participate in daily standup updates?', 'Methodology'),
    ('What is the major difference between a push system and a pull system in project management?', 'Methodology'),

    # Requirements
    ('How do you write good user stories?', 'Requirements'),
    ('What is the difference between a functional and non-functional requirement?', 'Requirements'),
    ("How specific should a user story's acceptance criteria be?", 'Requirements'),
    ("What does 'as a user, I want' actually need to include?", 'Requirements'),
    ("How do you gather requirements from a client who doesn't know what they want?", 'Requirements'),
    ('Is a use case diagram the same thing as a requirements document?', 'Requirements'),
    ('How do you prioritize conflicting requirements from different stakeholders?', 'Requirements'),
    ('What is requirement traceability and why does it matter?', 'Requirements'),
    ('How detailed should a requirements specification be for a small app?', 'Requirements'),
    ('What is the difference between a requirement and a feature?', 'Requirements'),
    ('How do you handle requirements that change after development starts?', 'Requirements'),
    ('What makes a requirement testable versus vague?', 'Requirements'),
    ('Should performance targets count as functional requirements?', 'Requirements'),
    ('How do you document requirements for a system with no UI?', 'Requirements'),
    ('What is the INVEST principle for user stories?', 'Requirements'),
    ('How do you validate requirements before development begins?', 'Requirements'),
    ("Is 'the system should be fast' a valid requirement at all?", 'Requirements'),
    ('How many user stories is too many for a single sprint?', 'Requirements'),
    ('What is a non-functional requirement example beyond speed?', 'Requirements'),
    ('How do you capture edge cases in a requirements document?', 'Requirements'),
    ('What is the difference between a business requirement and a system requirement?', 'Requirements'),
    ('How do you write an acceptance test from a single user story?', 'Requirements'),
    ('What is requirements elicitation and which techniques actually work?', 'Requirements'),
    ('How do you handle a requirement that conflicts with technical feasibility?', 'Requirements'),
    ('What is a use case versus a user story — are they interchangeable?', 'Requirements'),
    ("How do you know when a requirements document is 'done enough' to start coding?", 'Requirements'),
    ('What is scope creep and how do requirements documents prevent it?', 'Requirements'),
    ('How do you prioritize requirements when the client insists everything is critical?', 'Requirements'),
    ('What is a requirements baseline and why freeze it at all?', 'Requirements'),
    ('How do you capture implicit requirements the client never states directly?', 'Requirements'),
    ('What is the difference between a constraint and a requirement?', 'Requirements'),
    ('How do you validate a requirement without a working prototype yet?', 'Requirements'),
    ('What is requirements ambiguity and how do you resolve it early?', 'Requirements'),
    ('How do you handle requirements for a system replacing a legacy one?', 'Requirements'),
    ('What is a stakeholder requirement versus a solution requirement?', 'Requirements'),
    ('How do you differentiate between user requirements and system constraints?', 'Requirements'),
    ('What is the best way to document technical requirements for an asynchronous background job?', 'Requirements'),
    ('How do you write acceptance criteria using the Given-When-Then format?', 'Requirements'),
    ('What is the difference between a product backlog item and a functional requirement?', 'Requirements'),
    ('How do you handle a client who constantly changes the scope of a feature mid-sprint?', 'Requirements'),
    ('What is a software requirements specification (SRS) document and is it still useful?', 'Requirements'),
    ('How do you run a collaborative requirements workshop with non-technical stakeholders?', 'Requirements'),
    ('What makes a requirement ambiguous and how do you catch it during refinement?', 'Requirements'),
    ('Should infrastructure scaling targets be treated as non-functional requirements?', 'Requirements'),
    ('How do you map user stories to a visual user journey map to spot missing features?', 'Requirements'),

    # Testing
    ('Difference between verification and validation', 'Testing'),
    ('What is the difference between unit testing and integration testing?', 'Testing'),
    ('How do you decide what counts as a passing test case?', 'Testing'),
    ('Why does test coverage percentage not tell the whole story?', 'Testing'),
    ('What is regression testing and when should it run?', 'Testing'),
    ('How do you write a good test case for a login form?', 'Testing'),
    ('Is manual testing still worth doing if automated tests exist?', 'Testing'),
    ('What is the difference between black-box and white-box testing?', 'Testing'),
    ('How do you test something that depends on the current date?', 'Testing'),
    ('What is a mock object and why would you use one in a test?', 'Testing'),
    ('How many test cases are actually enough for a small feature?', 'Testing'),
    ('What is the difference between smoke testing and full regression testing?', 'Testing'),
    ('How do you test an API without a real database connection?', 'Testing'),
    ('What makes a bug report actually useful to a developer?', 'Testing'),
    ('Should QA write tests, or should developers write their own?', 'Testing'),
    ('What is boundary value analysis in testing?', 'Testing'),
    ("How do you test for edge cases you didn't think of?", 'Testing'),
    ("What does 'flaky test' mean and why is it a problem?", 'Testing'),
    ('How do you decide between manual and automated testing for a small team?', 'Testing'),
    ('What is user acceptance testing and who actually performs it?', 'Testing'),
    ('How do you test error handling without breaking the whole app?', 'Testing'),
    ('What is the difference between alpha testing and beta testing?', 'Testing'),
    ('How do you write a test plan before any code exists?', 'Testing'),
    ('What is exploratory testing and how does it differ from scripted testing?', 'Testing'),
    ('How do you measure the effectiveness of your test suite beyond coverage?', 'Testing'),
    ('What is the difference between a defect and a failure in testing terms?', 'Testing'),
    ('How do you test a feature that depends on a third-party API being available?', 'Testing'),
    ('What is performance testing actually measuring compared to load testing?', 'Testing'),
    ('How do you decide which tests to automate first on a legacy codebase?', 'Testing'),
    ('What is the difference between stub and mock in unit testing?', 'Testing'),
    ('How do you test concurrency issues that only show up under load?', 'Testing'),
    ('What is a test double and when would you use one over a real dependency?', 'Testing'),
    ('How do you structure a test suite so failures are easy to diagnose?', 'Testing'),
    ('What is mutation testing and is it worth the extra effort?', 'Testing'),
    ('How do you handle testing for accessibility compliance?', 'Testing'),
    ('What is the difference between functional and non-functional testing?', 'Testing'),
    ('What is the difference between component testing and system integration testing?', 'Testing'),
    ('How do you structure test cases for an application that handles complex financial transactions?', 'Testing'),
    ('What is property-based testing and how does it differ from example-based unit testing?', 'Testing'),
    ('How do you handle a test suite that runs too slowly to be included in a CI pipeline?', 'Testing'),
    ('What is the difference between data-driven testing and keyword-driven testing?', 'Testing'),
    ('How do you design a robust load testing scenario for a real-time chat application?', 'Testing'),
    ('What is path coverage and how does it differ from standard statement coverage?', 'Testing'),
    ('How do you isolate a flaky test that only fails when executed in the cloud environment?', 'Testing'),
    ('What is test-driven development (TDD) and what are its primary benefits?', 'Testing'),
    ('How do you perform security vulnerability scanning as part of automated testing?', 'Testing'),

    # Best Practices
    ('What makes a good code review?', 'Best Practices'),
    ("How long should a pull request realistically be before it's too big to review?", 'Best Practices'),
    ('What is the point of writing comments if the code is self-explanatory?', 'Best Practices'),
    ('How strict should naming conventions be enforced on a small team?', 'Best Practices'),
    ("Why is DRY (Don't Repeat Yourself) not always the right call?", 'Best Practices'),
    ('What makes a commit message actually useful six months later?', 'Best Practices'),
    ('How do you give critical feedback in a code review without sounding harsh?', 'Best Practices'),
    ('Is it bad practice to commit directly to the main branch?', 'Best Practices'),
    ('What is technical debt and when is it okay to take some on?', 'Best Practices'),
    ('How often should code actually be refactored?', 'Best Practices'),
    ('What is the single responsibility principle in practice, not theory?', 'Best Practices'),
    ('Should every function really have its own unit test?', 'Best Practices'),
    ('How do you keep a codebase consistent across multiple contributors?', 'Best Practices'),
    ('What is the difference between clean code and clever code?', 'Best Practices'),
    ("How small should a function be before it's considered too small?", 'Best Practices'),
    ('What is the value of a style guide if a linter already exists?', 'Best Practices'),
    ("How do you review code you don't fully understand yet?", 'Best Practices'),
    ('Why do senior developers still write so many small commits?', 'Best Practices'),
    ("What is the 'boy scout rule' in software engineering?", 'Best Practices'),
    ('How do you avoid over-engineering a simple feature?', 'Best Practices'),
    ('What is the difference between a code smell and an actual bug?', 'Best Practices'),
    ('How do you enforce consistent formatting across a team without arguments?', 'Best Practices'),
    ('What is the value of pair programming versus solo development?', 'Best Practices'),
    ('How do you decide when a class has too many responsibilities?', 'Best Practices'),
    ('What is the KISS principle and how do you apply it in practice?', 'Best Practices'),
    ('How do you handle legacy code with no tests and no documentation?', 'Best Practices'),
    ('What is the difference between defensive programming and paranoid programming?', 'Best Practices'),
    ('How often should dependencies actually be updated in a live project?', 'Best Practices'),
    ('What is the cost of ignoring compiler or linter warnings long-term?', 'Best Practices'),
    ("How do you write a README that's actually useful to a new contributor?", 'Best Practices'),
    ('What is the difference between a code review and a design review?', 'Best Practices'),
    ('How do you avoid premature optimization while still writing efficient code?', 'Best Practices'),
    ('What is the value of writing tests before the implementation exists?', 'Best Practices'),
    ('How do you keep documentation from going stale as code changes?', 'Best Practices'),
    ('What is the YAGNI principle and when does it actually apply?', 'Best Practices'),
    ('Why is over-abstraction considered a code smell in object-oriented programming?', 'Best Practices'),
    ('How do you enforce code style rules automatically using pre-commit Git hooks?', 'Best Practices'),
    ('What is the difference between composition and inheritance when designing reusable classes?', 'Best Practices'),
    ('How do you balance writing self-documenting code with adding inline code comments?', 'Best Practices'),
    ('What is the cost of leaving dead or unreachable code inside a production repository?', 'Best Practices'),
    ('How do you structure a pull request description so it is easy for a peer to review?', 'Best Practices'),
    ('What is semantic logging and why is it preferred over plain text error messages?', 'Best Practices'),
    ('How do you handle a legacy codebase that uses anti-patterns throughout its core logic?', 'Best Practices'),
    ('Why should magic numbers and hardcoded strings always be extracted into constants?', 'Best Practices'),
    ('What is the Open-Closed Principle and how do you implement it in a real-world scenario?', 'Best Practices'),

    # Tools
    ('Version control branching strategies for teams', 'Tools'),
    ('What is the difference between Git rebase and Git merge?', 'Tools'),
    ("How do you resolve a merge conflict without losing someone's changes?", 'Tools'),
    ('Is GitFlow overkill for a team of three?', 'Tools'),
    ('What is a feature branch and when should you delete it?', 'Tools'),
    ("How do you undo a commit that's already been pushed?", 'Tools'),
    ('What is the difference between git fetch and git pull?', 'Tools'),
    ('Should every developer have their own branch or share one?', 'Tools'),
    ("What does 'squash and merge' actually do to your commit history?", 'Tools'),
    ('How do you set up a CI pipeline for a small student project?', 'Tools'),
    ('What is the point of a .gitignore file exactly?', 'Tools'),
    ('How do you recover a deleted branch in Git?', 'Tools'),
    ('What tools do you actually need beyond Git for a group project?', 'Tools'),
    ('Is Trello enough for task tracking, or do we need something bigger?', 'Tools'),
    ('How do you handle secrets like API keys in a shared Git repo?', 'Tools'),
    ('What is the difference between a fork and a clone?', 'Tools'),
    ('How do you tag a release properly in Git?', 'Tools'),
    ('What is a Git hook and would we ever need one?', 'Tools'),
    ('How do you keep a long-lived branch from drifting too far from main?', 'Tools'),
    ("What is the safest way to force-push without breaking a teammate's work?", 'Tools'),
    ('What is the difference between Git stash and a temporary commit?', 'Tools'),
    ('How do you choose between GitHub Actions and Jenkins for CI?', 'Tools'),
    ('What is a monorepo and when does it make sense over multiple repos?', 'Tools'),
    ('How do you debug a merge conflict that touches the same line twice?', 'Tools'),
    ('What is the purpose of semantic versioning in a shared library?', 'Tools'),
    ('How do you set up pre-commit hooks to catch issues before pushing?', 'Tools'),
    ('What is the difference between a package manager and a build tool?', 'Tools'),
    ('How do you manage environment variables safely across dev and production?', 'Tools'),
    ('What is the point of a Dockerfile if the app already runs locally?', 'Tools'),
    ('How do you roll back a bad deployment quickly?', 'Tools'),
    ('What is the difference between continuous integration and continuous deployment?', 'Tools'),
    ('How do you choose an IDE versus a lightweight text editor for a team?', 'Tools'),
    ("What is a linter actually catching that a compiler wouldn't?", 'Tools'),
    ('How do you keep a shared development environment consistent across machines?', 'Tools'),
    ('What is the role of a package lock file in dependency management?', 'Tools'),
    ('What is the difference between Git cherry-pick and Git revert?', 'Tools'),
    ('How do you configure a web application to pull secrets safely from an external vault?', 'Tools'),
    ('What is the difference between a multi-stage Docker build and a single-stage build?', 'Tools'),
    ('How do you resolve a complex Git merge conflict that involves binary assets?', 'Tools'),
    ('What is infrastructure as code (IaC) and which tools are commonly used to manage it?', 'Tools'),
    ('How do you set up automatic deployments using GitHub Actions or GitLab CI?', 'Tools'),
    ('What is the difference between a package lockfile and a semantic version range tracker?', 'Tools'),
    ('How do you use a linter and a formatter together without configuration conflicts?', 'Tools'),
    ('What is the purpose of Git reflog and how can it save lost commits?', 'Tools'),
    ('How do you manage separate development, staging, and production environment configurations?', 'Tools'),

    # Web Development
    ('What is a REST API?', 'Web Development'),
    ('Difference between GET and POST in HTTP?', 'Web Development'),
    ('How does Laravel handle authentication?', 'Web Development'),
    ('What is the difference between server-side and client-side rendering?', 'Web Development'),
    ('How do cookies differ from sessions in a web app?', 'Web Development'),
    ('What is CORS and why does it keep blocking my requests?', 'Web Development'),
    ('How does a single-page application differ from a traditional website?', 'Web Development'),
    ('What is the purpose of middleware in a web framework?', 'Web Development'),
    ('How do you secure a form against CSRF attacks?', 'Web Development'),
    ('What is the difference between PUT and PATCH in a REST API?', 'Web Development'),
    ('How does routing actually work behind the scenes in Laravel?', 'Web Development'),
    ('What is the MVC pattern doing for us in a web app specifically?', 'Web Development'),
    ('How do you handle file uploads securely in a web form?', 'Web Development'),
    ('What is the difference between authentication and authorization?', 'Web Development'),
    ('How does JWT authentication differ from session-based login?', 'Web Development'),
    ('What is a webhook and how is it different from an API call?', 'Web Development'),
    ('How do you paginate results properly in an API response?', 'Web Development'),
    ('What is the purpose of an ORM like Eloquent?', 'Web Development'),
    ('How do you version an API without breaking existing clients?', 'Web Development'),
    ('What is the difference between a GET request with query params and a POST body?', 'Web Development'),
    ('What is the difference between a cookie and local storage?', 'Web Development'),
    ('How does server-side session management scale across multiple servers?', 'Web Development'),
    ('What is the purpose of an API gateway in a web architecture?', 'Web Development'),
    ('How do you handle rate limiting on a public API endpoint?', 'Web Development'),
    ('What is the difference between REST and GraphQL for an API?', 'Web Development'),
    ('How does a reverse proxy differ from a load balancer in a web stack?', 'Web Development'),
    ('What is the purpose of environment-specific configuration in a web app?', 'Web Development'),
    ('How do you secure an API endpoint that only admins should access?', 'Web Development'),
    ('What is the difference between a monolithic web app and a headless CMS setup?', 'Web Development'),
    ('How does browser caching affect how often a user re-downloads assets?', 'Web Development'),
    ('What is the purpose of a service worker in a modern web app?', 'Web Development'),
    ('How do you handle form validation on both client and server side?', 'Web Development'),
    ('What is the difference between synchronous and asynchronous form submission?', 'Web Development'),
    ("How does a content delivery network improve a website's load time?", 'Web Development'),
    ('What is the purpose of database connection pooling in a web app?', 'Web Development'),
    ('What is the difference between session cookies and local storage tokens for security?', 'Web Development'),
    ('How does a content delivery network route a user request to the nearest edge server?', 'Web Development'),
    ('What is the difference between HTTP long polling and WebSockets for real-time data?', 'Web Development'),
    ('How do you handle cross-origin resource sharing errors when building a decoupled frontend?', 'Web Development'),
    ('What is the difference between serverless functions and a traditional long-running server?', 'Web Development'),
    ('How do you implement secure password hashing using bcrypt inside a backend framework?', 'Web Development'),
    ('What is the purpose of database eager loading versus lazy loading in an ORM?', 'Web Development'),
    ('How does the browser rendering engine construct the DOM and CSSOM trees?', 'Web Development'),
    ('What is the difference between a state management library and a native context API?', 'Web Development'),
    ('How do you protect a public endpoint from malicious brute-force authentication attempts?', 'Web Development'),

    # Networking
    ('What does a 404 status code actually mean versus a 403?', 'Networking'),
    ('How does DNS resolve a domain name to an IP address?', 'Networking'),
    ('What is the difference between TCP and UDP?', 'Networking'),
    ('How does HTTPS actually encrypt traffic between client and server?', 'Networking'),
    ('What is a port number and why does it matter for networking?', 'Networking'),
    ('How does a load balancer decide which server to send a request to?', 'Networking'),
    ('What is the difference between a proxy and a VPN?', 'Networking'),
    ('How many round trips does a typical HTTPS handshake take?', 'Networking'),
    ('What is the OSI model actually useful for in practice?', 'Networking'),
    ('How does a firewall decide what traffic to block?', 'Networking'),
    ('What is latency versus bandwidth, and why do people confuse them?', 'Networking'),
    ('How does NAT allow multiple devices to share one public IP?', 'Networking'),
    ('What is the difference between HTTP/1.1 and HTTP/2?', 'Networking'),
    ('How do sockets actually maintain a persistent connection?', 'Networking'),
    ('What happens at the network layer when you type a URL and hit enter?', 'Networking'),
    ('What is the difference between a subnet mask and a gateway?', 'Networking'),
    ('How does a CDN reduce latency for users far from the origin server?', 'Networking'),
    ('What is packet loss and how does TCP recover from it?', 'Networking'),
    ('How does DHCP assign IP addresses automatically on a network?', 'Networking'),
    ('What is the difference between IPv4 and IPv6 in practical terms?', 'Networking'),
    ('What is the difference between unicast, multicast, and broadcast traffic?', 'Networking'),
    ('How does a three-way handshake establish a TCP connection?', 'Networking'),
    ('What is the purpose of a MAC address versus an IP address?', 'Networking'),
    ('How does traceroute figure out the path a packet takes?', 'Networking'),
    ('What is the difference between a switch and a router?', 'Networking'),
    ('How does ARP resolve an IP address to a physical address?', 'Networking'),
    ('What is bandwidth throttling and how does a network enforce it?', 'Networking'),
    ('How does a VPN tunnel actually protect traffic on a public network?', 'Networking'),
    ('What is the difference between symmetric and asymmetric encryption in HTTPS?', 'Networking'),
    ('How does a network handle two devices with the same IP address?', 'Networking'),
    ('What is QoS (Quality of Service) and why does it matter for streaming traffic?', 'Networking'),
    ('How does a subnet determine how many devices a network can support?', 'Networking'),
    ('What is the difference between a public and private IP address?', 'Networking'),
    ('How does packet fragmentation happen and why can it cause issues?', 'Networking'),
    ('What is the purpose of a DNS cache and how long do entries usually last?', 'Networking'),
    ('How does a router determine the optimal path for a packet across autonomous systems?', 'Networking'),
    ('What is the difference between symmetric and asymmetric routing on a network?', 'Networking'),
    ('How do TLS certificates establish a trust chain between a browser and a server?', 'Networking'),
    ('What is the purpose of the Time-to-Live field inside an IP packet header?', 'Networking'),
    ('How does an application layer proxy differ from a network layer firewall?', 'Networking'),
    ('What is the difference between a stateful firewall and a stateless firewall?', 'Networking'),
    ('How do network sockets manage data flow control using the TCP window size?', 'Networking'),
    ('What is the purpose of a reverse DNS lookup and when is it used?', 'Networking'),
    ('How does a network switch learn which physical devices are connected to its ports?', 'Networking'),
    ('What is the difference between an authoritative name server and a recursive resolver?', 'Networking'),

    # Programming
    ('What is the difference between OOP and FP?', 'Programming'),
    ('When should I use an interface vs abstract class?', 'Programming'),
    ('What is the difference between a compiler and an interpreter?', 'Programming'),
    ('How does recursion actually work under the hood with the call stack?', 'Programming'),
    ('What is the difference between pass-by-value and pass-by-reference?', 'Programming'),
    ('Why does static typing catch bugs that dynamic typing misses?', 'Programming'),
    ('What is a closure and why is it useful in practice?', 'Programming'),
    ('How do you decide between an array and a linked list for a task?', 'Programming'),
    ('What is the time complexity of common sorting algorithms?', 'Programming'),
    ('How does garbage collection actually free up memory?', 'Programming'),
    ('What is the difference between synchronous and asynchronous code?', 'Programming'),
    ('How do you avoid null reference errors in a large codebase?', 'Programming'),
    ('What is a generic type and when would you actually need one?', 'Programming'),
    ('How does polymorphism differ from method overloading?', 'Programming'),
    ('What is the difference between a stack and a queue in practice?', 'Programming'),
    ('How do you decide when a problem needs dynamic programming?', 'Programming'),
    ('What is the difference between a shallow copy and a deep copy?', 'Programming'),
    ("How does exception handling differ across languages you've used?", 'Programming'),
    ('What makes a recursive solution better or worse than an iterative one?', 'Programming'),
    ('How do you reason about Big O when two algorithms look similar?', 'Programming'),
    ('What is the difference between an abstract data type and a data structure?', 'Programming'),
    ('How does memory allocation differ between the stack and the heap?', 'Programming'),
    ('What is the difference between a mutable and immutable object?', 'Programming'),
    ('How do you decide between iteration and recursion for a given problem?', 'Programming'),
    ('What is duck typing and how does it differ from static typing?', 'Programming'),
    ('How does a hash table achieve near-constant time lookups?', 'Programming'),
    ('What is the difference between a compile-time error and a runtime error?', 'Programming'),
    ('How do you reason about thread safety in concurrent code?', 'Programming'),
    ('What is the difference between eager and lazy evaluation?', 'Programming'),
    ('How does type coercion cause unexpected bugs in loosely typed languages?', 'Programming'),
    ('What is the difference between a value type and a reference type?', 'Programming'),
    ('How do you avoid memory leaks in a language without automatic garbage collection?', 'Programming'),
    ('What is tail call optimization and which languages actually support it?', 'Programming'),
    ('How does operator overloading affect code readability?', 'Programming'),
    ('What is the difference between an interface and a protocol across languages?', 'Programming'),
    ('What is the difference between a structural type system and a nominal type system?', 'Programming'),
    ('How do closures capture and maintain access to outer variables in memory?', 'Programming'),
    ('What is the runtime difference between a process, a thread, and a coroutine?', 'Programming'),
    ('How does a compiler perform dead code elimination during the optimization phase?', 'Programming'),
    ('What is the difference between a hash map and a tree map in terms of time complexity?', 'Programming'),
    ('How do you safely handle arithmetic overflow errors in strongly typed languages?', 'Programming'),
    ('What is a memory leak and how do you track it down in a managed memory environment?', 'Programming'),
    ('How does an asynchronous event loop execute non-blocking input and output operations?', 'Programming'),
    ('What is the difference between standard covariance and contravariance in generic types?', 'Programming'),
    ('How does a structural pattern match differ from a traditional switch-case block?', 'Programming'),

    # Architecture
    ('Explain the MVC design pattern', 'Architecture'),
    ('What is the difference between monolithic and microservices architecture?', 'Architecture'),
    ('How does the observer pattern actually get used in real applications?', 'Architecture'),
    ('What is the singleton pattern and why is it sometimes considered bad practice?', 'Architecture'),
    ('How do you decide between a layered architecture and a modular one?', 'Architecture'),
    ("What is the repository pattern solving that a plain query wouldn't?", 'Architecture'),
    ('How does dependency injection actually reduce coupling?', 'Architecture'),
    ('What is the difference between tight coupling and loose coupling?', 'Architecture'),
    ('How do event-driven architectures differ from request-response ones?', 'Architecture'),
    ('What is the factory pattern actually useful for in practice?', 'Architecture'),
    ('How do you decide where business logic should live in an MVC app?', 'Architecture'),
    ('What is the difference between a service layer and a controller?', 'Architecture'),
    ('How does the strategy pattern help avoid long if-else chains?', 'Architecture'),
    ('What are the tradeoffs of a microservices architecture for a small team?', 'Architecture'),
    ('How do you design a system to scale horizontally instead of vertically?', 'Architecture'),
    ('What is separation of concerns actually achieving in a real project?', 'Architecture'),
    ('How does the adapter pattern help integrate two incompatible systems?', 'Architecture'),
    ('What is the difference between a facade pattern and an API gateway?', 'Architecture'),
    ('How do you avoid circular dependencies between modules?', 'Architecture'),
    ("What makes an architecture 'clean' versus just organized?", 'Architecture'),
    ('What is the difference between a hexagonal architecture and a layered one?', 'Architecture'),
    ('How do you decide the boundaries between microservices in a system?', 'Architecture'),
    ('What is CQRS and when does it actually add value over a simple CRUD design?', 'Architecture'),
    ('How does an event bus differ from direct service-to-service calls?', 'Architecture'),
    ('What is the difference between a domain model and a data model?', 'Architecture'),
    ('How do you design for eventual consistency in a distributed system?', 'Architecture'),
    ("What is the builder pattern solving that a constructor alone wouldn't?", 'Architecture'),
    ('How does a message queue decouple two parts of a system?', 'Architecture'),
    ('What is the difference between vertical and horizontal scaling in architecture terms?', 'Architecture'),
    ("How do you design an API that's backward compatible as the system evolves?", 'Architecture'),
    ('What is the decorator pattern used for in practice?', 'Architecture'),
    ('How does domain-driven design influence how you structure a codebase?', 'Architecture'),
    ('What is the difference between a bounded context and a module?', 'Architecture'),
    ('How do you architect a system to tolerate a single service going down?', 'Architecture'),
    ('What is the command pattern and when does it actually simplify code?', 'Architecture'),
    ('What is the difference between event sourcing and standard database state persistence?', 'Architecture'),
    ('How do you handle transactions that span across multiple microservices safely?', 'Architecture'),
    ('What is the difference between the API gateway pattern and the Backends-for-Frontends pattern?', 'Architecture'),
    ('How does the dependency inversion principle decouple a high-level domain from its database?', 'Architecture'),
    ('What are the architectural tradeoffs of adopting a shared database multi-tenancy model?', 'Architecture'),
    ('How do you implement a circuit breaker pattern to prevent cascading system failures?', 'Architecture'),
    ('What is the difference between a data lake, a data warehouse, and a standard operational database?', 'Architecture'),
    ('How does service discovery work inside a dynamic containerized cloud architecture?', 'Architecture'),
    ('What is the purpose of a command bus pattern in a clean architecture system?', 'Architecture'),
    ('How do you transition a legacy monolithic architecture to a modular monolith design?', 'Architecture'),

    # Database
    ('How do foreign keys work in MySQL?', 'Database'),
    ('Explain normalisation with examples', 'Database'),
    ('Denormalization — when is it actually a good idea?', 'Database'),
    ('What is the difference between a primary key and a unique key?', 'Database'),
    ('How does indexing actually speed up a query?', 'Database'),
    ('What is the difference between INNER JOIN and LEFT JOIN?', 'Database'),
    ('When should you use a composite key instead of a single-column key?', 'Database'),
    ('What is a transaction and why does it need to be atomic?', 'Database'),
    ('How do you decide between SQL and NoSQL for a project?', 'Database'),
    ('What is the N+1 query problem and how do you avoid it?', 'Database'),
    ('How does a database enforce referential integrity?', 'Database'),
    ('What is the difference between a view and a materialized view?', 'Database'),
    ('How do you design a schema for a many-to-many relationship?', 'Database'),
    ('What is database sharding and when would you actually need it?', 'Database'),
    ('How does an ORM translate object relationships into SQL joins?', 'Database'),
    ('What is the difference between DELETE and TRUNCATE in SQL?', 'Database'),
    ('How do you optimize a slow query with a large dataset?', 'Database'),
    ('What is a deadlock in a database and how do you avoid one?', 'Database'),
    ('How does ACID compliance differ across database engines?', 'Database'),
    ('What is the difference between a clustered and non-clustered index?', 'Database'),
    ('What is the difference between a stored procedure and a function in SQL?', 'Database'),
    ('How does database replication improve read performance?', 'Database'),
    ('What is the CAP theorem and how does it apply to database design?', 'Database'),
    ('How do you design a schema to support soft deletes without breaking queries?', 'Database'),
    ('What is the difference between optimistic and pessimistic locking?', 'Database'),
    ('How does a covering index reduce the need to read the full row?', 'Database'),
    ('What is the difference between a full table scan and an index scan?', 'Database'),
    ('How do you handle a many-to-many relationship with extra attributes on the join?', 'Database'),
    ('What is database partitioning and when does a table actually need it?', 'Database'),
    ('How does a database handle concurrent writes to the same row?', 'Database'),
    ('What is the difference between eventual consistency and strong consistency?', 'Database'),
    ('How do you migrate a production database schema without downtime?', 'Database'),
    ('What is a self-referencing foreign key used for in practice?', 'Database'),
    ('How does query caching differ from result set caching?', 'Database'),
    ('What is the difference between a surrogate key and a natural key?', 'Database'),
    ('What is the difference between a primary index, a secondary index, and a composite index?', 'Database'),
    ('How does write-ahead logging guarantee data persistence during an unexpected system crash?', 'Database'),
    ('What is the difference between the read committed and repeatable read isolation levels?', 'Database'),
    ('How do you track down and resolve a hidden deadlock issue in a production database?', 'Database'),
    ('What is connection pooling and why is it critical for handling high concurrent traffic?', 'Database'),
    ('How do you handle structural database migrations across a clustered database cluster?', 'Database'),
    ('What is the difference between document-oriented databases and wide-column store databases?', 'Database'),
    ('How does a relational database management system execute a join query under the hood?', 'Database'),
    ('What is a database index scan versus an index seek, and which is faster?', 'Database'),
    ('How do you implement soft deletes using a global query scope to prevent accidental data leaks?', 'Database'),

    # Numerical Analysis
    ('Newton-Raphson method explained simply', 'Numerical Analysis'),
    ('When does the bisection method fail to converge?', 'Numerical Analysis'),
    ('How do you choose a good initial guess for Newton-Raphson?', 'Numerical Analysis'),
    ('What is the difference between bisection and the false position method?', 'Numerical Analysis'),
    ('Why does Newton-Raphson fail when the derivative is zero?', 'Numerical Analysis'),
    ('How many iterations does bisection typically need for a given tolerance?', 'Numerical Analysis'),
    ('What is the secant method and how does it differ from Newton-Raphson?', 'Numerical Analysis'),
    ('How do you know a root-finding method has actually converged?', 'Numerical Analysis'),
    ('What is the order of convergence and why does it matter here?', 'Numerical Analysis'),
    ('How does the fixed-point iteration method find a root?', 'Numerical Analysis'),
    ('Why might Newton-Raphson converge to the wrong root entirely?', 'Numerical Analysis'),
    ('What is the difference between open and bracketing root-finding methods?', 'Numerical Analysis'),
    ('How do you handle a function with multiple roots in the same interval?', 'Numerical Analysis'),
    ('What causes oscillation in the false position method?', 'Numerical Analysis'),
    ('How sensitive is Newton-Raphson to the initial guess compared to bisection?', 'Numerical Analysis'),
    ('What is the stopping criterion typically used for root-finding algorithms?', 'Numerical Analysis'),
    ('How do you find complex roots using numerical methods?', 'Numerical Analysis'),
    ('Why is bisection considered more reliable but slower than Newton-Raphson?', 'Numerical Analysis'),
    ('What happens if you apply Newton-Raphson to a function with no real root?', 'Numerical Analysis'),
    ('How do you verify a computed root is accurate enough?', 'Numerical Analysis'),
    ("Trapezoidal vs Simpson's rule for integration", 'Numerical Analysis'),
    ('How does the trapezoidal rule approximate the area under a curve?', 'Numerical Analysis'),
    ("Why does Simpson's rule generally give more accurate results?", 'Numerical Analysis'),
    ('What is the error bound for the trapezoidal rule?', 'Numerical Analysis'),
    ('How many subintervals are enough for a reliable numerical integration?', 'Numerical Analysis'),
    ("What is the difference between Simpson's 1/3 rule and 3/8 rule?", 'Numerical Analysis'),
    ('How does numerical integration handle a function with a discontinuity?', 'Numerical Analysis'),
    ("What is Romberg integration and how does it improve on Simpson's rule?", 'Numerical Analysis'),
    ('How do you numerically integrate a function with no closed-form antiderivative?', 'Numerical Analysis'),
    ('What causes numerical integration to lose accuracy with too few intervals?', 'Numerical Analysis'),
    ('How does Gaussian quadrature differ from the trapezoidal rule?', 'Numerical Analysis'),
    ('What is the midpoint rule and how does it compare to the trapezoidal rule?', 'Numerical Analysis'),
    ('How do you estimate the error in a numerical integration result?', 'Numerical Analysis'),
    ('Why does increasing subintervals not always improve accuracy?', 'Numerical Analysis'),
    ("What is composite Simpson's rule and why is it used over the basic version?", 'Numerical Analysis'),
    ('How does numerical integration apply to real-world engineering problems?', 'Numerical Analysis'),
    ('What is the difference between definite and indefinite numerical integration?', 'Numerical Analysis'),
    ("How do you choose between trapezoidal and Simpson's rule for a given function?", 'Numerical Analysis'),
    ('What happens to accuracy when a function oscillates rapidly?', 'Numerical Analysis'),
    ('How is numerical integration used to estimate area under a probability curve?', 'Numerical Analysis'),
    ('What is adaptive quadrature and how does it decide interval size?', 'Numerical Analysis'),
    ('How does the secant method avoid computing the analytical derivative of a function?', 'Numerical Analysis'),
    ('What causes numerical underflow when multiplying many small probabilities together?', 'Numerical Analysis'),
    ('What is the difference between local truncation error and global truncation error?', 'Numerical Analysis'),
    ('How does the choice of interval size affect the stability of the trapezoidal rule?', 'Numerical Analysis'),
    ('Why do rounding errors compound more quickly in single-precision floating-point numbers?', 'Numerical Analysis'),
    ('What is the difference between the open Newton-Cotes formula and the closed formula?', 'Numerical Analysis'),
    ('How does adaptive quadrature automatically adjust the size of integration subintervals?', 'Numerical Analysis'),
    ('Why does the bisection method guarantee convergence while open methods do not?', 'Numerical Analysis'),
    ('What is ill-conditioning in a mathematical problem and how does it affect numerical stability?', 'Numerical Analysis'),
    ('How does Romberg integration use Richardson extrapolation to achieve higher accuracy?', 'Numerical Analysis'),
]

CATEGORIES = sorted(set(category for _, category in TRAINING_DATA))


def as_lists():
    """Convenience helper: returns (texts, labels) as two parallel lists,
    ready for sklearn's train_test_split or a vectorizer."""
    texts, labels = zip(*TRAINING_DATA)
    return list(texts), list(labels)


if __name__ == '__main__':
    from collections import Counter
    counts = Counter(cat for _, cat in TRAINING_DATA)
    print(f"{len(TRAINING_DATA)} examples across {len(CATEGORIES)} categories")
    for cat in CATEGORIES:
        print(f"  {cat}: {counts[cat]}")