# Training data for the topic classifier — 11 categories, 806 examples.
# July 2026: expanded with targeted examples; 'Best Practices' removed
# after error analysis; label audit fixed 3 labels and 1 duplicate.

TRAINING_DATA = [
    ('What is a mutex and how does it protect a critical section?', 'Programming'),
    ('How does a two pointer technique solve array problems efficiently?', 'Programming'),
    ('How do you build a like button that updates the count instantly?', 'Web Development'),
    ('What is the difference between flexbox and CSS grid for page layout?', 'Web Development'),
    ('What is the difference between the API gateway pattern and the Backends-for-Frontends pattern?', 'Architecture'),
    ('What is the purpose of the SYN and ACK flags in a TCP segment?', 'Networking'),
    ('How do you handle a many-to-many relationship with extra attributes on the join?', 'Database'),
    ('What is the difference between output and outcome in planning?', 'Methodology'),
    ('What is Xdebug and how do you step through PHP code with it?', 'Tools'),
    ('How does an iterator differ from directly indexing a collection?', 'Programming'),
    ('What is semantic HTML and why do heading levels matter?', 'Web Development'),
    ('How does a VPN tunnel actually protect traffic on a public network?', 'Networking'),
    ('What is the testing pyramid and why are UI tests at the top?', 'Testing'),
    ('How does a database handle concurrent writes to the same row?', 'Database'),
    ('What triggers moving from the design phase into implementation?', 'SDLC'),
    ('What is exploratory testing and how is a session structured?', 'Testing'),
    ('How do you handle a test suite that runs too slowly to be included in a CI pipeline?', 'Testing'),
    ('How does a load balancer decide which server to send a request to?', 'Networking'),
    ('What is CIDR notation and how do you read a /24 subnet?', 'Networking'),
    ('Should performance targets count as functional requirements?', 'Requirements'),
    ('How do you handle transactions that span across multiple microservices safely?', 'Architecture'),
    ('What is the purpose of a cumulative flow diagram in a Kanban workflow?', 'Methodology'),
    ('How does snapshot testing catch unintended output changes?', 'Testing'),
    ('How does an ORM translate object relationships into SQL joins?', 'Database'),
    ('What is the difference between a fork and a clone?', 'Tools'),
    ('How do you tag a release properly in Git?', 'Tools'),
    ('What is the difference between a surrogate key and a natural key?', 'Database'),
    ('Difference between GET and POST in HTTP?', 'Web Development'),
    ('What is the difference between PUT and PATCH in a REST API?', 'Web Development'),
    ('What are the tradeoffs of a microservices architecture for a small team?', 'Architecture'),
    ('What is the Agile Manifesto actually saying in plain terms?', 'Methodology'),
    ('How does a captive portal intercept traffic on public WiFi?', 'Networking'),
    ('What is the difference between concurrency and parallelism?', 'Programming'),
    ('How do you manage separate development, staging, and production environment configurations?', 'Tools'),
    ('What is the difference between a stateful firewall and a stateless firewall?', 'Networking'),
    ('What is a dev container and how does it standardize onboarding?', 'Tools'),
    ('How do you show old input values after a failed form validation?', 'Web Development'),
    ('How does a single-page application differ from a traditional website?', 'Web Development'),
    ('What happens when a team games its velocity numbers?', 'Methodology'),
    ('How does docker compose start several services with one command?', 'Tools'),
    ('How do you configure a web application to pull secrets safely from an external vault?', 'Tools'),
    ('What is the difference between the read committed and repeatable read isolation levels?', 'Database'),
    ('How does adaptive quadrature automatically adjust the size of integration subintervals?', 'Numerical Analysis'),
    ('What is contract testing between a consumer and a provider?', 'Testing'),
    ('What is backlog grooming and how often should it happen?', 'Methodology'),
    ('How does LU decomposition reuse work across multiple solves?', 'Numerical Analysis'),
    ('How do you numerically integrate a function with no closed-form antiderivative?', 'Numerical Analysis'),
    ('What is the difference between git fetch and git pull?', 'Tools'),
    ('What are the architectural tradeoffs of adopting a shared database multi-tenancy model?', 'Architecture'),
    ('How does the EXPLAIN plan show why a query is slow?', 'Database'),
    ('What is the point of a sprint review if stakeholders rarely attend?', 'Methodology'),
    ('How do you manage environment variables safely across dev and production?', 'Tools'),
    ('What is the difference between FTP and SFTP for transferring files?', 'Networking'),
    ('What is the difference between a hexagonal architecture and a layered one?', 'Architecture'),
    ('What is a Docker volume and how does it persist data between runs?', 'Tools'),
    ('What is the difference between vertical and horizontal scaling in architecture terms?', 'Architecture'),
    ('How does a message queue decouple two parts of a system?', 'Architecture'),
    ('What is the difference between an interface and a protocol across languages?', 'Programming'),
    ('What is DNS cache poisoning and how is it prevented?', 'Networking'),
    ('How do you test an API without a real database connection?', 'Testing'),
    ('When does the bisection method fail to converge?', 'Numerical Analysis'),
    ('What is the cost of fixing a defect found late versus early in the lifecycle?', 'SDLC'),
    ('What is the purpose of environment-specific configuration in a web app?', 'Web Development'),
    ('Version control branching strategies for teams', 'Tools'),
    ('How do you handle testing for accessibility compliance?', 'Testing'),
    ('What is path coverage and how does it differ from standard statement coverage?', 'Testing'),
    ('What is the major difference between a push system and a pull system in project management?', 'Methodology'),
    ('Which SDLC phase is most often underestimated by new teams?', 'SDLC'),
    ('What is a build artifact and where does a pipeline store it?', 'Tools'),
    ('How does Kanban differ from Scrum in daily practice?', 'Methodology'),
    ('What is the difference between open and bracketing root-finding methods?', 'Numerical Analysis'),
    ('What is the definition of ready versus the definition of done?', 'Methodology'),
    ('How does the mediator pattern reduce direct object-to-object chatter?', 'Architecture'),
    ('Can the testing phase overlap with the implementation phase?', 'SDLC'),
    ('What is the difference between IPv4 and IPv6 in practical terms?', 'Networking'),
    ('What is the difference between component testing and system integration testing?', 'Testing'),
    ('What is ill-conditioning in a mathematical problem and how does it affect numerical stability?', 'Numerical Analysis'),
    ('What is vertical slicing of features versus horizontal layers?', 'Methodology'),
    ('What layers of caching typically sit between an application and its data store?', 'Architecture'),
    ('How does domain-driven design influence how you structure a codebase?', 'Architecture'),
    ('How do race conditions happen with shared mutable state?', 'Programming'),
    ('What is the difference between synchronous and asynchronous form submission?', 'Web Development'),
    ('How do you implement soft deletes using a global query scope to prevent accidental data leaks?', 'Database'),
    ('How do you seed dropdown options from a database table in a form?', 'Web Development'),
    ("How does Euler's method step through a differential equation?", 'Numerical Analysis'),
    ("How does a release train coordinate multiple teams' schedules?", 'Methodology'),
    ('How does Laravel handle authentication?', 'Web Development'),
    ('How does a change request travel through the lifecycle after release?', 'SDLC'),
    ('How do you alias long commands in your shell configuration?', 'Tools'),
    ('How does a compiler perform dead code elimination during the optimization phase?', 'Programming'),
    ('What is the difference between TCP and UDP?', 'Networking'),
    ('What is a DNS A record versus a CNAME record?', 'Networking'),
    ('What is the point of a Dockerfile if the app already runs locally?', 'Tools'),
    ('How does pattern matching simplify branching on data shapes?', 'Programming'),
    ('How does ICMP differ from TCP and UDP?', 'Networking'),
    ('What is the purpose of an ORM like Eloquent?', 'Web Development'),
    ('How do you know when a phase is actually complete?', 'SDLC'),
    ('How do closures capture and maintain access to outer variables in memory?', 'Programming'),
    ('What risks come from rushing the requirements phase?', 'SDLC'),
    ('How does Lagrange interpolation build a polynomial through points?', 'Numerical Analysis'),
    ('What is the difference between a value type and a reference type?', 'Programming'),
    ('What is the difference between event sourcing and standard database state persistence?', 'Architecture'),
    ('How does a TLS handshake negotiate which cipher suite to use?', 'Networking'),
    ('What is the loopback address 127.0.0.1 actually for?', 'Networking'),
    ('How do you decide between an array and a linked list for a task?', 'Programming'),
    ('Does every project need to go through all SDLC phases in order?', 'SDLC'),
    ('How does pair rotation spread knowledge across a team?', 'Methodology'),
    ('How does a priority queue differ from a normal queue?', 'Programming'),
    ('What is the difference between DELETE and TRUNCATE in SQL?', 'Database'),
    ('What is the difference between session cookies and local storage tokens for security?', 'Web Development'),
    ('What is equivalence partitioning in test case design?', 'Testing'),
    ('What is the difference between functional and non-functional testing?', 'Testing'),
    ('What is the difference between a subnet mask and a gateway?', 'Networking'),
    ('How does milestone planning work in a plan-driven project?', 'Methodology'),
    ('What is git LFS and when do large files need it?', 'Tools'),
    ("How does a content delivery network improve a website's load time?", 'Networking'),
    ('How do you sign commits and why would a project require it?', 'Tools'),
    ('How do you choose between orchestration and choreography for workflows?', 'Architecture'),
    ('How do you use git bisect to find the commit that broke a feature?', 'Tools'),
    ("What is the difference between Simpson's 1/3 rule and 3/8 rule?", 'Numerical Analysis'),
    ('What is the proxy pattern and how does it differ from decorator?', 'Architecture'),
    ('How do you decide the right SDLC model for a fixed-budget client project?', 'SDLC'),
    ('What is the difference between eventual consistency and strong consistency?', 'Database'),
    ('How do you estimate the timeline for each SDLC phase?', 'SDLC'),
    ('What is the role of demos in keeping stakeholders engaged?', 'Methodology'),
    ('How many user stories is too many for a single sprint?', 'Requirements'),
    ('What is the role of the client during the lifecycle stages?', 'SDLC'),
    ('Is Trello enough for task tracking, or do we need something bigger?', 'Tools'),
    ('What is the difference between tight coupling and loose coupling?', 'Architecture'),
    ('How does the null object pattern remove repetitive existence checks?', 'Architecture'),
    ('How does the strategy pattern help avoid long if-else chains?', 'Architecture'),
    ('How do you show a loading spinner while an AJAX request is running?', 'Web Development'),
    ('What is tmux useful for when working over SSH?', 'Tools'),
    ('How do you measure the effectiveness of your test suite beyond coverage?', 'Testing'),
    ('How does the lifecycle handle software retirement or decommissioning?', 'SDLC'),
    ('What is an enum and when is it better than string constants?', 'Programming'),
    ('What is the purpose of database connection pooling in a web app?', 'Web Development'),
    ('How many test cases are actually enough for a small feature?', 'Testing'),
    ('How do you display validation errors next to each form field?', 'Web Development'),
    ("What is server-side validation catching that client-side validation can't?", 'Web Development'),
    ("How do you debounce a live search box so it doesn't fire on every keystroke?", 'Web Development'),
    ('What is the difference between localStorage and a JavaScript variable for page state?', 'Web Development'),
    ('What is certificate pinning and what problem does it solve?', 'Networking'),
    ('How do you estimate the error in a numerical integration result?', 'Numerical Analysis'),
    ('What belongs in a definition of done for a student project?', 'Methodology'),
    ('What is a transaction and why does it need to be atomic?', 'Database'),
    ('How do you map user stories to a visual user journey map to spot missing features?', 'Requirements'),
    ('How does service discovery work inside a dynamic containerized cloud architecture?', 'Architecture'),
    ('How do you resolve a detached HEAD state without losing work?', 'Tools'),
    ('How does the adapter pattern help integrate two incompatible systems?', 'Architecture'),
    ('What is the difference between a structural type system and a nominal type system?', 'Programming'),
    ('What is a Python virtual environment and why activate one per project?', 'Tools'),
    ('What causes oscillation in the false position method?', 'Numerical Analysis'),
    ('What does git clean remove and how do you dry run it first?', 'Tools'),
    ('What is the MVC pattern doing for us in a web app specifically?', 'Architecture'),
    ('How long should each SDLC phase realistically take for a small project?', 'SDLC'),
    ('What is the difference between smoke testing and full regression testing?', 'Testing'),
    ('How do you redirect a user back to the page they came from after login?', 'Web Development'),
    ('How do you migrate a column type on a table with millions of rows?', 'Database'),
    ('What is an ER diagram showing about entities and relationships?', 'Database'),
    ('How does anycast let many servers share one IP address?', 'Networking'),
    ('What is the difference between UNION and UNION ALL?', 'Database'),
    ('What is scope creep and how do requirements documents prevent it?', 'Requirements'),
    ('How do you make a navbar collapse into a hamburger menu on mobile?', 'Web Development'),
    ('How does the concept of a sprint goal prevent scope creep during development?', 'Methodology'),
    ('Explain normalisation with examples', 'Database'),
    ('What does the ping command actually measure?', 'Networking'),
    ('How does the lifecycle change for a maintenance-only project?', 'SDLC'),
    ('What is the difference between a view and a materialized view?', 'Database'),
    ('What are the risks of merging the development and testing phases into one continuous loop?', 'SDLC'),
    ('What is the purpose of middleware in a web framework?', 'Web Development'),
    ('How does packet fragmentation happen and why can it cause issues?', 'Networking'),
    ('How do you avoid circular dependencies between modules?', 'Architecture'),
    ('How does a subnet determine how many devices a network can support?', 'Networking'),
    ('How do you decide between a layered architecture and a modular one?', 'Architecture'),
    ('Difference between verification and validation', 'Testing'),
    ('Why does static typing catch bugs that dynamic typing misses?', 'Programming'),
    ('What is the role of an Agile coach compared to a standard Scrum Master?', 'Methodology'),
    ('How do you export a table on a page to CSV from the browser?', 'Web Development'),
    ('How is a socket identified by an IP address and port pair?', 'Networking'),
    ('How do you store hierarchical data like categories in SQL?', 'Database'),
    ('How do network sockets manage data flow control using the TCP window size?', 'Networking'),
    ("How does the template method pattern share an algorithm's skeleton?", 'Architecture'),
    ('Is GitFlow overkill for a team of three?', 'Tools'),
    ("What is composite Simpson's rule and why is it used over the basic version?", 'Numerical Analysis'),
    ('How does DHCP assign IP addresses automatically on a network?', 'Networking'),
    ('How do you validate a requirement without a working prototype yet?', 'Requirements'),
    ('What is the difference between OOP and FP?', 'Programming'),
    ('What is a spike story and when does a team schedule one?', 'Methodology'),
    ('How do you close a sprint that clearly will not finish its goal?', 'Methodology'),
    ('How do bug fixes get prioritized against new feature work?', 'Methodology'),
    ('What is the decorator pattern used for in practice?', 'Architecture'),
    ('How does BGP decide routes between internet providers?', 'Networking'),
    ('What is the difference between a data lake, a data warehouse, and a standard operational database?', 'Database'),
    ("How do you undo a commit that's already been pushed?", 'Tools'),
    ('How do you define clear entrance and exit criteria for the implementation phase?', 'SDLC'),
    ('How do you decide when a problem needs dynamic programming?', 'Programming'),
    ('How do you decide what counts as a passing test case?', 'Testing'),
    ("Trapezoidal vs Simpson's rule for integration", 'Numerical Analysis'),
    ('What is the best way to document technical requirements for an asynchronous background job?', 'Requirements'),
    ('How do you enforce code style rules automatically using pre-commit Git hooks?', 'Tools'),
    ('What is the difference between a GET request with query params and a POST body?', 'Web Development'),
    ('How does a structural pattern match differ from a traditional switch-case block?', 'Programming'),
    ("What does 'squash and merge' actually do to your commit history?", 'Tools'),
    ('What is the difference between npm install and npm ci?', 'Tools'),
    ('Should QA write tests, or should developers write their own?', 'Testing'),
    ('What is the difference between @include and @extends in a template?', 'Web Development'),
    ('What is the difference between a hash map and a tree map in terms of time complexity?', 'Programming'),
    ('What is Postman useful for when testing an API by hand?', 'Tools'),
    ('How do you generate a URL slug from a post title?', 'Web Development'),
    ('How do you use a linter and a formatter together without configuration conflicts?', 'Tools'),
    ('How is numerical integration used to estimate area under a probability curve?', 'Numerical Analysis'),
    ('How do you publish a package to a registry for the first time?', 'Tools'),
    ('How do you plan for the maintenance phase before the product even ships?', 'SDLC'),
    ('What is the ambassador pattern in service-to-service communication?', 'Architecture'),
    ('What is the time complexity of common sorting algorithms?', 'Programming'),
    ('How does wireless interference affect throughput on a WiFi network?', 'Networking'),
    ("How do you know when a requirements document is 'done enough' to start coding?", 'Requirements'),
    ('How do you handle a client who constantly changes the scope of a feature mid-sprint?', 'Methodology'),
    ('What are isolation levels and what anomalies does each prevent?', 'Database'),
    ('How do you set up a code coverage report in a CI run?', 'Tools'),
    ('How do user feedback loops affect the maintenance phase of a production system?', 'SDLC'),
    ('Is Extreme Programming (XP) still used anywhere today?', 'Methodology'),
    ('What are classes of service on a Kanban board?', 'Methodology'),
    ('How do you handle secrets like API keys in a shared Git repo?', 'Tools'),
    ('What is the difference between a public and private IP address?', 'Networking'),
    ('How does the browser rendering engine construct the DOM and CSSOM trees?', 'Web Development'),
    ('Should every developer have their own branch or share one?', 'Tools'),
    ('How does Gaussian elimination solve a linear system step by step?', 'Numerical Analysis'),
    ('How do you architect a system to tolerate a single service going down?', 'Architecture'),
    ('How do TLS certificates establish a trust chain between a browser and a server?', 'Networking'),
    ('How do you decide the boundaries between microservices in a system?', 'Architecture'),
    ('How does a relational database management system execute a join query under the hood?', 'Database'),
    ('What is the anti-corruption layer protecting a clean domain from?', 'Architecture'),
    ('What is the difference between an abstract data type and a data structure?', 'Programming'),
    ('How does Gaussian quadrature differ from the trapezoidal rule?', 'Numerical Analysis'),
    ('What is the difference between a service layer and a controller?', 'Architecture'),
    ('How does write-ahead logging guarantee data persistence during an unexpected system crash?', 'Database'),
    ('What is the singleton pattern and why is it sometimes considered bad practice?', 'Architecture'),
    ('What is the biggest weakness of Scrum for a two-person team?', 'Methodology'),
    ('What is a mock object and why would you use one in a test?', 'Testing'),
    ('How many iterations does bisection typically need for a given tolerance?', 'Numerical Analysis'),
    ('How do you handle cross-origin resource sharing errors when building a decoupled frontend?', 'Web Development'),
    ('How do you document requirements for a system with no UI?', 'Requirements'),
    ('How do you keep a footer stuck to the bottom on short pages?', 'Web Development'),
    ("What is the builder pattern solving that a constructor alone wouldn't?", 'Architecture'),
    ('What is backpressure and how does a processing pipeline apply it?', 'Architecture'),
    ('How does a system stay responsive using asynchronous message handling?', 'Architecture'),
    ("How does exception handling differ across languages you've used?", 'Programming'),
    ('What is the runtime difference between a process, a thread, and a coroutine?', 'Programming'),
    ('How does server-side session management scale across multiple servers?', 'Web Development'),
    ('How does SSH tunneling carry traffic through a restricted network?', 'Networking'),
    ('How does a team measure predictability rather than raw speed?', 'Methodology'),
    ('What is a non-goal section and why include one in a specification?', 'Requirements'),
    ('How do you decide where business logic should live in an MVC app?', 'Architecture'),
    ('How detailed should a requirements specification be for a small app?', 'Requirements'),
    ('What is requirements elicitation and which techniques actually work?', 'Requirements'),
    ('How does the trapezoidal rule approximate the area under a curve?', 'Numerical Analysis'),
    ('What is the difference between the open Newton-Cotes formula and the closed formula?', 'Numerical Analysis'),
    ('How does the dependency inversion principle decouple a high-level domain from its database?', 'Architecture'),
    ('What is mutation testing and is it worth the extra effort?', 'Testing'),
    ('What is a self-referencing foreign key used for in practice?', 'Database'),
    ('What happens during a post-mortem review at the end of a product release?', 'SDLC'),
    ('How do you manage dependencies between multiple teams working in the same sprint?', 'Methodology'),
    ('How does keepalive stop an idle TCP connection from closing?', 'Networking'),
    ('What is the difference between INNER JOIN and LEFT JOIN?', 'Database'),
    ('How do you handle structural database migrations across a clustered database cluster?', 'Database'),
    ('What outputs does the implementation phase hand over to testing?', 'SDLC'),
    ('How does a team of students divide roles fairly on a group project?', 'Methodology'),
    ('How does deployment differ between a big bang and a phased rollout?', 'SDLC'),
    ('How do you test a feature that depends on a third-party API being available?', 'Testing'),
    ('What is the difference between storing images in the database and on disk?', 'Web Development'),
    ('What is the difference between optimistic and pessimistic locking?', 'Database'),
    ('How does the unit of work pattern group changes into one commit?', 'Architecture'),
    ("What does 'flaky test' mean and why is it a problem?", 'Testing'),
    ('What is bandwidth throttling and how does a network enforce it?', 'Networking'),
    ('What is a monorepo and when does it make sense over multiple repos?', 'Tools'),
    ('What is the memento pattern and how does undo functionality use it?', 'Architecture'),
    ('What is truncation error versus rounding error?', 'Numerical Analysis'),
    ("What is the spiral model's risk analysis step actually assessing?", 'SDLC'),
    ('What is the difference between continuous integration and continuous deployment?', 'Tools'),
    ('How does polymorphism differ from method overloading?', 'Programming'),
    ('What is the difference between a hash map and a binary search tree?', 'Programming'),
    ('What is the N+1 query problem and how do you avoid it?', 'Database'),
    ('What makes a bug report actually useful to a developer?', 'Testing'),
    ('How does numerical integration apply to real-world engineering problems?', 'Numerical Analysis'),
    ('What is the difference between HAVING and WHERE in a query?', 'Database'),
    ('What is the purpose of semantic versioning in a shared library?', 'Tools'),
    ('Why does UDP suit live video streaming better than TCP?', 'Networking'),
    ('What is connection pooling and why is it critical for handling high concurrent traffic?', 'Database'),
    ('What is a deadlock in a database and how do you avoid one?', 'Database'),
    ('Can a solo developer meaningfully follow Scrum at all?', 'Methodology'),
    ('What is the difference between symmetric and asymmetric routing on a network?', 'Networking'),
    ('What is eventual consistency asking the user interface to tolerate?', 'Architecture'),
    ('How does garbage collection actually free up memory?', 'Programming'),
    ('What is the factory pattern actually useful for in practice?', 'Architecture'),
    ('What is the strangler fig approach to replacing a legacy system?', 'Architecture'),
    ('What is the sliding window protocol in reliable data transfer?', 'Networking'),
    ('What is the difference between document-oriented databases and wide-column store databases?', 'Database'),
    ('How does a content delivery network route a user request to the nearest edge server?', 'Networking'),
    ('How do WIP limits change how a Kanban team works?', 'Methodology'),
    ('How does a router determine the optimal path for a packet across autonomous systems?', 'Networking'),
    ('How do routing tables decide the next hop for a packet?', 'Networking'),
    ('How do you write acceptance criteria using the Given-When-Then format?', 'Requirements'),
    ("How do you gather requirements from a client who doesn't know what they want?", 'Requirements'),
    ('What is the difference between unicast, multicast, and broadcast traffic?', 'Networking'),
    ('What tools do you actually need beyond Git for a group project?', 'Tools'),
    ('What is scope creep and how does a process keep it in check?', 'Methodology'),
    ('How do you handle form validation on both client and server side?', 'Web Development'),
    ('What is the difference between system design and detailed design?', 'SDLC'),
    ('What is a database cursor and when should you iterate instead of fetching everything?', 'Database'),
    ('What is property-based testing and how does it differ from example-based unit testing?', 'Testing'),
    ('How does a VLAN separate traffic on the same physical switch?', 'Networking'),
    ('How does T-shirt sizing compare to story points for estimates?', 'Methodology'),
    ('What happens to accuracy when a function oscillates rapidly?', 'Numerical Analysis'),
    ('How does a team decide its sprint commitment realistically?', 'Methodology'),
    ('How does CI caching make pipeline runs faster?', 'Tools'),
    ('What is the purpose of a MAC address versus an IP address?', 'Networking'),
    ('What is mutation testing measuring about a test suite?', 'Testing'),
    ('What are the tradeoffs between one week and three week sprints?', 'Methodology'),
    ('How do you design a schema for a many-to-many relationship?', 'Database'),
    ('What documentation is expected at the end of each SDLC stage?', 'SDLC'),
    ('What is a database GUI client useful for beyond running queries?', 'Tools'),
    ('What is a state machine and when does explicit state design pay off?', 'Architecture'),
    ('How do quality attributes like availability drive structural decisions?', 'Architecture'),
    ('What is the difference between an interactive rebase and a normal one?', 'Tools'),
    ('What is the difference between a partial view and a layout?', 'Web Development'),
    ('What is the order of convergence and why does it matter here?', 'Numerical Analysis'),
    ('How do you onboard a new member mid-sprint without derailing it?', 'Methodology'),
    ("How do you keep two services' contracts stable while both evolve?", 'Architecture'),
    ('What is the difference between half duplex and full duplex communication?', 'Networking'),
    ("What is the safest way to force-push without breaking a teammate's work?", 'Tools'),
    ('Is a use case diagram the same thing as a requirements document?', 'Requirements'),
    ('What is a bulkhead pattern and what failure does it contain?', 'Architecture'),
    ('How do you plan sprint capacity around holidays and part-time members?', 'Methodology'),
    ('How do you handle a requirement that conflicts with technical feasibility?', 'Requirements'),
    ('What is a lambda expression and where do anonymous functions shine?', 'Programming'),
    ('How do you design a robust load testing scenario for a real-time chat application?', 'Testing'),
    ('What does git blame tell you about a single line of code?', 'Tools'),
    ('What is the difference between a requirement and a feature?', 'Requirements'),
    ('What is the difference between a business requirement and a system requirement?', 'Requirements'),
    ('How does routing actually work behind the scenes in Laravel?', 'Web Development'),
    ('How do you mirror a repository to a second remote?', 'Tools'),
    ('What is the point of a .gitignore file exactly?', 'Tools'),
    ('What is a requirements review meeting actually checking for?', 'Requirements'),
    ('What is tail recursion and can the compiler optimize it away?', 'Programming'),
    ('Should infrastructure scaling targets be treated as non-functional requirements?', 'Requirements'),
    ('Explain the MVC design pattern', 'Architecture'),
    ('How do you find complex roots using numerical methods?', 'Numerical Analysis'),
    ('How do you set up pre-commit hooks to catch issues before pushing?', 'Tools'),
    ('What is the difference between a bounded context and a module?', 'Architecture'),
    ('How do you handle a team member who refuses to participate in daily standup updates?', 'Methodology'),
    ('How do requirements gathering and system design connect in the lifecycle?', 'SDLC'),
    ('What is the difference between a package manager and a build tool?', 'Tools'),
    ('What is a planning poker session and how does it improve estimation accuracy?', 'Methodology'),
    ('What are the main drawbacks of using Scrumban for a rapidly growing team?', 'Methodology'),
    ('What is a requirements baseline and why freeze it at all?', 'Requirements'),
    ('What is the difference between business rules and requirements?', 'Requirements'),
    ('How does numerical integration handle a function with a discontinuity?', 'Numerical Analysis'),
    ('How do you debug a merge conflict that touches the same line twice?', 'Tools'),
    ('How does NAT allow multiple devices to share one public IP?', 'Networking'),
    ('How do you isolate a flaky test that only fails when executed in the cloud environment?', 'Testing'),
    ('What does a typical sprint planning meeting look like?', 'Methodology'),
    ('What is the difference between a stored procedure and a function in SQL?', 'Database'),
    ('How does a switch statement compare to a lookup table for dispatching?', 'Programming'),
    ('How does type coercion cause unexpected bugs in loosely typed languages?', 'Programming'),
    ('How does indexing actually speed up a query?', 'Database'),
    ('How do you perform security vulnerability scanning as part of automated testing?', 'Testing'),
    ('Why does increasing subintervals not always improve accuracy?', 'Numerical Analysis'),
    ('What is the difference between Git rebase and Git merge?', 'Tools'),
    ('What is user acceptance testing and who actually performs it?', 'Testing'),
    ('How do git worktrees let you check out two branches at once?', 'Tools'),
    ('What is an abstract method forcing every subclass to implement?', 'Programming'),
    ('How do you reproduce a bug that only appears with production data?', 'Testing'),
    ('How do you size a backlog item that nobody has estimated before?', 'Methodology'),
    ('How do exceptions propagate up the call stack?', 'Programming'),
    ("Why does Simpson's rule generally give more accurate results?", 'Numerical Analysis'),
    ('How does query caching differ from result set caching?', 'Database'),
    ('How do you handle a phase that fails its exit criteria?', 'SDLC'),
    ('What is a port number and why does it matter for networking?', 'Networking'),
    ('What is timeboxing and why does Agile rely on it so heavily?', 'Methodology'),
    ('How does operator overloading affect code readability?', 'Programming'),
    ('How do security requirements change the standard phases of the SDLC?', 'SDLC'),
    ('What is a component diagram showing that a class diagram does not?', 'Architecture'),
    ('How does database replication improve read performance?', 'Database'),
    ('What is the difference between HTTP/1.1 and HTTP/2?', 'Networking'),
    ('How does SMTP hand a message from one mail server to another?', 'Networking'),
    ('What is a memory leak and how do you track it down in a managed memory environment?', 'Programming'),
    ('How many round trips does a typical HTTPS handshake take?', 'Networking'),
    ('What is the difference between a package lockfile and a semantic version range tracker?', 'Tools'),
    ('How do you model a one-to-one relationship without wasting a table?', 'Database'),
    ('What is the Scaled Agile Framework (SAFe) trying to solve?', 'Methodology'),
    ('How do you run a collaborative requirements workshop with non-technical stakeholders?', 'Requirements'),
    ('What is a closure and why is it useful in practice?', 'Programming'),
    ('Is Lean the same thing as Agile or something different?', 'Methodology'),
    ('What is the difference between a roadmap and a release plan?', 'Methodology'),
    ('Why do some networks block all ports except 80 and 443?', 'Networking'),
    ('Can someone explain the phases of SDLC with a real example?', 'SDLC'),
    ('What is the difference between the SDLC and a software process model?', 'SDLC'),
    ('What is a shared kernel between two bounded contexts?', 'Architecture'),
    ('How do personas keep requirements grounded in real users?', 'Requirements'),
    ('How do you transition a legacy monolithic architecture to a modular monolith design?', 'Architecture'),
    ('Agile vs Waterfall — which is better for small teams?', 'Methodology'),
    ('What is the purpose of a post-implementation review?', 'SDLC'),
    ('What is the difference between a hotfix branch and a release branch?', 'Tools'),
    ('How does a database handle two transactions updating the same row?', 'Database'),
    ('What is the difference between a monolithic web app and a headless CMS setup?', 'Web Development'),
    ('What is database sharding and when would you actually need it?', 'Database'),
    ('What is the difference between pass-by-value and pass-by-reference?', 'Programming'),
    ('How do you avoid memory leaks in a language without automatic garbage collection?', 'Programming'),
    ('Why is bisection considered more reliable but slower than Newton-Raphson?', 'Numerical Analysis'),
    ('What is requirements elicitation versus requirements analysis?', 'Requirements'),
    ("What is Simpson's rule and when is it more accurate?", 'Numerical Analysis'),
    ('What is the INVEST principle for user stories?', 'Requirements'),
    ('What is the purpose of a DNS cache and how long do entries usually last?', 'Networking'),
    ('Is manual testing still worth doing if automated tests exist?', 'Testing'),
    ('What is the difference between unit testing and integration testing?', 'Testing'),
    ('How do you keep a Kanban board from growing unlimited work-in-progress?', 'Methodology'),
    ('How does ACID compliance differ across database engines?', 'Database'),
    ('What is separation of concerns actually achieving in a real project?', 'Architecture'),
    ('How do story points actually get estimated in Scrum?', 'Methodology'),
    ('What is the maximum transmission unit and why does an MTU mismatch break connections?', 'Networking'),
    ('What is idempotency and why do retried operations need it?', 'Architecture'),
    ('What is the difference between Scrum and Scrumban?', 'Methodology'),
    ('Why do some teams fail when adopting Agile too quickly?', 'Methodology'),
    ('How do you reason about Big O when two algorithms look similar?', 'Programming'),
    ('How do you attach the VS Code debugger and set a breakpoint?', 'Tools'),
    ('What is the OSI model actually useful for in practice?', 'Networking'),
    ('How do you decide between SQL and NoSQL for a project?', 'Database'),
    ('How does memory allocation differ between the stack and the heap?', 'Programming'),
    ('How do you choose a good initial guess for Newton-Raphson?', 'Numerical Analysis'),
    ('What is a stub versus a spy in test doubles?', 'Testing'),
    ('What is the difference between a stack and a queue in practice?', 'Programming'),
    ('What is the difference between a primary key and a unique key?', 'Database'),
    ('What is the purpose of the Time-to-Live field inside an IP packet header?', 'Networking'),
    ("How do you test for edge cases you didn't think of?", 'Testing'),
    ('How do you safely handle arithmetic overflow errors in strongly typed languages?', 'Programming'),
    ('How does HTTPS actually encrypt traffic between client and server?', 'Networking'),
    ('How do you optimize a slow query with a large dataset?', 'Database'),
    ('How do you carve a monolith along seams without a full rewrite?', 'Architecture'),
    ('Why does the bisection method guarantee convergence while open methods do not?', 'Numerical Analysis'),
    ('What is the difference between black-box and white-box testing?', 'Testing'),
    ('What is a feature branch and when should you delete it?', 'Tools'),
    ('What is requirements ambiguity and how do you resolve it early?', 'Requirements'),
    ('How does the secant method avoid computing the analytical derivative of a function?', 'Numerical Analysis'),
    ('What is the difference between data-driven testing and keyword-driven testing?', 'Testing'),
    ('How does a DDoS attack overwhelm a server with traffic?', 'Networking'),
    ('How do you handle a function with multiple roots in the same interval?', 'Numerical Analysis'),
    ('How does browser caching affect how often a user re-downloads assets?', 'Web Development'),
    ("Is 'the system should be fast' a valid requirement at all?", 'Requirements'),
    ('What does a 404 status code actually mean versus a 403?', 'Networking'),
    ('What is the difference between bisection and the false position method?', 'Numerical Analysis'),
    ('What is a default gateway and what happens without one?', 'Networking'),
    ('How do sockets actually maintain a persistent connection?', 'Networking'),
    ('How does a network switch learn which physical devices are connected to its ports?', 'Networking'),
    ('What is the secant method and how does it differ from Newton-Raphson?', 'Numerical Analysis'),
    ('What happens if you skip the planning phase entirely?', 'SDLC'),
    ('What is the difference between a functional design and a technical design document?', 'SDLC'),
    ("What makes an architecture 'clean' versus just organized?", 'Architecture'),
    ('How do you verify a computed root is accurate enough?', 'Numerical Analysis'),
    ('What is the DOMContentLoaded event and when does it fire?', 'Web Development'),
    ('What is boundary value analysis in testing?', 'Testing'),
    ('What is the difference between synchronous and asynchronous code?', 'Programming'),
    ('How do you decide between iteration and recursion for a given problem?', 'Programming'),
    ('How does the chain of responsibility pattern route a request through handlers?', 'Architecture'),
    ('What is a Git hook and would we ever need one?', 'Tools'),
    ('What is optimistic UI updating and when is it safe to use?', 'Web Development'),
    ('How do you capture implicit requirements the client never states directly?', 'Requirements'),
    ('How do you write a test plan before any code exists?', 'Testing'),
    ('What is the difference between monolithic and microservices architecture?', 'Architecture'),
    ('What is the difference between a mutable and immutable object?', 'Programming'),
    ('How do you test pagination edge cases like an empty last page?', 'Testing'),
    ('What is a software requirements specification (SRS) document and is it still useful?', 'Requirements'),
    ('What is swarming on a single work item and when does it help?', 'Methodology'),
    ('What is the difference between HTTP long polling and WebSockets for real-time data?', 'Web Development'),
    ('What happens at the network layer when you type a URL and hit enter?', 'Networking'),
    ('How does traceroute figure out the path a packet takes?', 'Networking'),
    ('What is the difference between a shallow copy and a deep copy?', 'Programming'),
    ('How do check constraints enforce rules the application might forget?', 'Database'),
    ('How does the choice of interval size affect the stability of the trapezoidal rule?', 'Numerical Analysis'),
    ('What is the purpose of a reverse DNS lookup and when is it used?', 'Networking'),
    ('What is the difference between iterative and linear lifecycle models?', 'SDLC'),
    ('What is adaptive quadrature and how does it decide interval size?', 'Numerical Analysis'),
    ('How does a language implement string immutability under the hood?', 'Programming'),
    ('How do you handle requirements for a system replacing a legacy one?', 'Requirements'),
    ('How does a CDN reduce latency for users far from the origin server?', 'Networking'),
    ('Newton-Raphson method explained simply', 'Numerical Analysis'),
    ("What is Romberg integration and how does it improve on Simpson's rule?", 'Numerical Analysis'),
    ("What does 'done' actually mean in a Scrum board column?", 'Methodology'),
    ('How do you choose between GitHub Actions and Jenkins for CI?', 'Tools'),
    ('How do you prioritize requirements when the client insists everything is critical?', 'Requirements'),
    ('What is route model binding and how does it clean up controllers?', 'Web Development'),
    ('How does a hash table achieve near-constant time lookups?', 'Programming'),
    ('What happens to the SDLC when a project is cancelled mid-phase?', 'SDLC'),
    ('How does a network handle two devices with the same IP address?', 'Networking'),
    ('How does the SDLC differ for embedded systems versus web apps?', 'SDLC'),
    ('What is the difference between a modem and a router in a home setup?', 'Networking'),
    ('How does a covering index reduce the need to read the full row?', 'Database'),
    ('What is the role of a quality assurance lead during the initial planning phase?', 'SDLC'),
    ('What is the purpose of a service worker in a modern web app?', 'Web Development'),
    ('What is the difference between definite and indefinite numerical integration?', 'Numerical Analysis'),
    ('How does the V-model pair testing activities with development phases?', 'SDLC'),
    ('How does the V-model pair each phase with a testing level?', 'SDLC'),
    ('What is packet capture and what can you learn from inspecting raw packets?', 'Networking'),
    ('What is the difference between a full table scan and an index scan?', 'Database'),
    ('How does boundary value analysis pick test inputs?', 'Testing'),
    ('How do database triggers fire and why can they surprise you?', 'Database'),
    ('How does JWT authentication differ from session-based login?', 'Web Development'),
    ('What is the difference between a switch and a router?', 'Networking'),
    ('How does the Jacobi iterative method approach a solution?', 'Numerical Analysis'),
    ('What is the difference between a Scrum Master and a Project Manager?', 'Methodology'),
    ('When should I use an interface vs abstract class?', 'Programming'),
    ('What are media queries and how do breakpoints work in responsive design?', 'Web Development'),
    ('What is the difference between watch mode and a one-off build?', 'Tools'),
    ('What is the difference between a multi-stage Docker build and a single-stage build?', 'Tools'),
    ('What is the difference between symmetric and asymmetric encryption in HTTPS?', 'Networking'),
    ('How do you build a dropdown that filters a table without reloading the page?', 'Web Development'),
    ('How do you test error handling without breaking the whole app?', 'Testing'),
    ('What is the difference between local truncation error and global truncation error?', 'Numerical Analysis'),
    ('How do you make a data table accessible to screen readers?', 'Web Development'),
    ('What is packet loss and how does TCP recover from it?', 'Networking'),
    ('Why might Newton-Raphson converge to the wrong root entirely?', 'Numerical Analysis'),
    ('How do you profile a slow function to find the bottleneck?', 'Tools'),
    ('What is the command pattern and when does it actually simplify code?', 'Architecture'),
    ('How is the maintenance phase different from the deployment phase?', 'SDLC'),
    ('What is a self join and when do you actually need one?', 'Database'),
    ('How do you test concurrency issues that only show up under load?', 'Testing'),
    ('How do you build a dark mode toggle that remembers the choice?', 'Web Development'),
    ('How does the visitor pattern add operations without touching existing classes?', 'Architecture'),
    ('How do you keep a shared development environment consistent across machines?', 'Tools'),
    ("How do you choose between trapezoidal and Simpson's rule for a given function?", 'Numerical Analysis'),
    ('How does a publish subscribe model differ from a work queue?', 'Architecture'),
    ('What is a git submodule and when is it more trouble than help?', 'Tools'),
    ('How do you structure a test suite so failures are easy to diagnose?', 'Testing'),
    ('How do you handle file uploads securely in a web form?', 'Web Development'),
    ('Which lifecycle phase produces the user manual and training documents?', 'SDLC'),
    ('Why do some companies add a dedicated feasibility study phase?', 'SDLC'),
    ('Can you mix Agile and Waterfall on the same project?', 'Methodology'),
    ('How do you lazy load images so a long page renders faster?', 'Web Development'),
    ('What is a database index scan versus an index seek, and which is faster?', 'Database'),
    ('How does Feature-Driven Development differ from Scrum?', 'Methodology'),
    ('How does a reverse proxy differ from a load balancer in a web stack?', 'Networking'),
    ('How do window functions differ from GROUP BY aggregates?', 'Database'),
    ('What is a CSRF token actually checking when a form posts?', 'Web Development'),
    ("How do you resolve a merge conflict without losing someone's changes?", 'Tools'),
    ('What is database seeding useful for beyond testing?', 'Database'),
    ('How do you write a good test case for a login form?', 'Testing'),
    ('What is a minimum viable product cut from a full requirement set?', 'Requirements'),
    ('How do you run a pre-mortem before starting a risky project?', 'Methodology'),
    ('What is Richardson extrapolation squeezing extra accuracy from?', 'Numerical Analysis'),
    ('How does operator overloading work and when is it abused?', 'Programming'),
    ('What is the difference between REST and GraphQL for an API?', 'Web Development'),
    ('What is a non-functional requirement example beyond speed?', 'Requirements'),
    ('How do you reason about thread safety in concurrent code?', 'Programming'),
    ('Denormalization — when is it actually a good idea?', 'Database'),
    ('How do standups avoid turning into status reports?', 'Methodology'),
    ('What is requirement traceability and why does it matter?', 'Requirements'),
    ('What is the point of a retrospective if nothing changes afterward?', 'Methodology'),
    ('What is the error bound for the trapezoidal rule?', 'Numerical Analysis'),
    ('How does a database enforce referential integrity?', 'Database'),
    ('What is an operational handover checklist at the end of deployment?', 'SDLC'),
    ('How does an asynchronous event loop execute non-blocking input and output operations?', 'Programming'),
    ('How do you migrate a production database schema without downtime?', 'Database'),
    ('What is an ill-conditioned matrix and why do small input changes explode?', 'Numerical Analysis'),
    ("What does 'as a user, I want' actually need to include?", 'Requirements'),
    ('How do you set up a CI pipeline for a small student project?', 'Tools'),
    ('When should you use a composite key instead of a single-column key?', 'Database'),
    ('How does a covering index avoid touching the table at all?', 'Database'),
    ('How do you version an API without breaking existing clients?', 'Web Development'),
    ('What causes numerical integration to lose accuracy with too few intervals?', 'Numerical Analysis'),
    ('What makes a requirement ambiguous and how do you catch it during refinement?', 'Requirements'),
    ('What does Dependabot actually open pull requests for?', 'Tools'),
    ('What is the role of a package lock file in dependency management?', 'Tools'),
    ('How do you pin a dependency to an exact version and why?', 'Tools'),
    ('What is latency versus bandwidth, and why do people confuse them?', 'Networking'),
    ('What is the difference between authentication and authorization?', 'Web Development'),
    ('How does a traceroute hop count reveal where latency comes from?', 'Networking'),
    ('What is progressive enhancement versus graceful degradation in a UI?', 'Web Development'),
    ('What makes a recursive solution better or worse than an iterative one?', 'Programming'),
    ('How does full text search differ from a LIKE query?', 'Database'),
    ('How do you run a daily standup for a distributed team across time zones?', 'Methodology'),
    ('How does a bounded context decide which team owns which model?', 'Architecture'),
    ('Why does Waterfall struggle with changing requirements?', 'Methodology'),
    ('What is the role of a product owner versus a project manager in Agile?', 'Methodology'),
    ('What deliverables come out of the analysis phase?', 'SDLC'),
    ('How do regulatory constraints become requirements in a specification?', 'Requirements'),
    ('What is CORS and why does it keep blocking my requests?', 'Web Development'),
    ("How do you validate a file upload's type and size before saving it?", 'Web Development'),
    ('How do you retroactively document a project that skipped formal phases?', 'SDLC'),
    ('What is the difference between a compile-time error and a runtime error?', 'Programming'),
    ('What is reference class forecasting and how does it reduce optimistic estimates?', 'Methodology'),
    ('What is a REST API?', 'Web Development'),
    ('How do you handle rate limiting on a public API endpoint?', 'Web Development'),
    ('What is the difference between a constraint and a requirement?', 'Requirements'),
    ('How do you know a root-finding method has actually converged?', 'Numerical Analysis'),
    ('What is a broadcast storm and how does a network prevent one?', 'Networking'),
    ('How do you track down and resolve a hidden deadlock issue in a production database?', 'Database'),
    ('What retrospective formats keep the meeting from going stale?', 'Methodology'),
    ('How does a saga coordinate a long-running distributed workflow?', 'Architecture'),
    ('What is the difference between an authoritative name server and a recursive resolver?', 'Networking'),
    ('What is the difference between Git stash and a temporary commit?', 'Tools'),
    ('What is mob programming and when does it beat pairing?', 'Methodology'),
    ('What is a ports and adapters structure isolating the domain from?', 'Architecture'),
    ('How do you design a schema to support soft deletes without breaking queries?', 'Database'),
    ('How does DNS over HTTPS change what your ISP can see?', 'Networking'),
    ('What is a modular monolith and how strict should module boundaries be?', 'Architecture'),
    ('What is a test double and when would you use one over a real dependency?', 'Testing'),
    ('How do you implement a remember me checkbox on a login form?', 'Web Development'),
    ('What is the midpoint rule and how does it compare to the trapezoidal rule?', 'Numerical Analysis'),
    ('What is the difference between a product backlog item and a functional requirement?', 'Requirements'),
    ('How do you differentiate between user requirements and system constraints?', 'Requirements'),
    ('How does a mesh network route around a failed node?', 'Networking'),
    ('What is a burndown chart actually telling you?', 'Methodology'),
    ('What causes numerical underflow when multiplying many small probabilities together?', 'Numerical Analysis'),
    ('Why do some organizations prefer the Lean software development framework over Scrum?', 'Methodology'),
    ('What is the resize cost difference between a linked list and a dynamic array?', 'Programming'),
    ('How do you version internal contracts between modules?', 'Architecture'),
    ('How do you paginate results properly in an API response?', 'Web Development'),
    ('How often should sprints actually be — one week or two?', 'Methodology'),
    ('What is a webhook and how is it different from an API call?', 'Web Development'),
    ('How does an application layer proxy differ from a network layer firewall?', 'Networking'),
    ('How does dependency injection actually reduce coupling?', 'Architecture'),
    ('What is an asynchronous standup and when does it beat a live meeting?', 'Methodology'),
    ('Is there a standard number of phases every SDLC must have?', 'SDLC'),
    ('Why do rounding errors compound more quickly in single-precision floating-point numbers?', 'Numerical Analysis'),
    ('How do you avoid null reference errors in a large codebase?', 'Programming'),
    ('What does npm audit report and how do you fix what it finds?', 'Tools'),
    ('What is the software development lifecycle?', 'SDLC'),
    ('How does hairpin NAT let a device reach a server on its own local network?', 'Networking'),
    ('How does the fetch API differ from submitting a form the normal way?', 'Web Development'),
    ('What is performance testing actually measuring compared to load testing?', 'Testing'),
    ('What is the difference between a facade pattern and an API gateway?', 'Architecture'),
    ('What is the difference between a design pattern and an architectural style?', 'Architecture'),
    ('What is the role of sign-off at the end of each phase?', 'SDLC'),
    ('What is the difference between a soft delete and a hard delete in schema design?', 'Database'),
    ('What is the difference between cycle time and lead time?', 'Methodology'),
    ('What is QoS (Quality of Service) and why does it matter for streaming traffic?', 'Networking'),
    ('How do you validate requirements before development begins?', 'Requirements'),
    ('What is jitter and how does it affect a voice call?', 'Networking'),
    ('What is test-driven development (TDD) and what are its primary benefits?', 'Testing'),
    ('What is port forwarding and when do you need it on a home router?', 'Networking'),
    ('How do you design graceful degradation when a dependency is down?', 'Architecture'),
    ('Why do we need a separate design phase before coding starts?', 'SDLC'),
    ('What is memoization and how does it speed up recursion?', 'Programming'),
    ('What is exploratory testing and how does it differ from scripted testing?', 'Testing'),
    ('What is the difference between a primary index, a secondary index, and a composite index?', 'Database'),
    ('What is integer overflow and how do languages handle it differently?', 'Programming'),
    ('What does the Gauss-Seidel method converge faster than?', 'Numerical Analysis'),
    ('How do you run a stakeholder interview that surfaces real needs?', 'Requirements'),
    ('What is duck typing and what tradeoffs does it bring?', 'Programming'),
    ('What is a flaky test and how do you stabilize one?', 'Testing'),
    ('What is a use case versus a user story — are they interchangeable?', 'Requirements'),
    ('What is the difference between the SDLC and the SDLC model chosen for a project?', 'SDLC'),
    ('How do you build a multi step form wizard that keeps state between steps?', 'Web Development'),
    ('How do you secure an API endpoint that only admins should access?', 'Web Development'),
    ('What is the difference between latency and round trip time exactly?', 'Networking'),
    ('How many subintervals are enough for a reliable numerical integration?', 'Numerical Analysis'),
    ('How does a Kanban replenishment meeting decide what enters the board?', 'Methodology'),
    ('How do you design for eventual consistency in a distributed system?', 'Architecture'),
    ("How do you design an API that's backward compatible as the system evolves?", 'Architecture'),
    ('How do you measure velocity accurately across sprints?', 'Methodology'),
    ('How do branch protection rules stop direct pushes to main?', 'Tools'),
    ('What is a system context diagram capturing at the boundary?', 'Requirements'),
    ('How do you spot a solution disguised as a requirement?', 'Requirements'),
    ('How do you handle mid-sprint priority changes from a stakeholder?', 'Methodology'),
    ('How do you decide between manual and automated testing for a small team?', 'Testing'),
    ('How do you capture edge cases in a requirements document?', 'Requirements'),
    ('When would Waterfall actually be the right choice over Agile?', 'Methodology'),
    ('How do you write good user stories?', 'Requirements'),
    ('How does Romberg integration use Richardson extrapolation to achieve higher accuracy?', 'Numerical Analysis'),
    ('What is the difference between WPA2 and WPA3 encryption on WiFi?', 'Networking'),
    ('Why does test coverage percentage not tell the whole story?', 'Testing'),
    ('What is a stored procedure and when does logic belong in the database?', 'Database'),
    ('How does lazy evaluation defer work until a value is needed?', 'Programming'),
    ('What is the purpose of a command bus pattern in a clean architecture system?', 'Architecture'),
    ('How do you send a POST request with curl from the terminal?', 'Tools'),
    ('What is database partitioning and when does a table actually need it?', 'Database'),
    ('What is a Makefile and why do teams still use them?', 'Tools'),
    ('What is the difference between serverless functions and a traditional long-running server?', 'Web Development'),
    ('What is event delegation in JavaScript and why use it for long lists?', 'Web Development'),
    ('How do maintenance categories like corrective and adaptive differ?', 'SDLC'),
    ('What is the purpose of an API gateway in a web architecture?', 'Web Development'),
    ("What is Newton's divided difference interpolation used for?", 'Numerical Analysis'),
    ('What is the purpose of database eager loading versus lazy loading in an ORM?', 'Web Development'),
    ('How do you test something that depends on the current date?', 'Testing'),
    ('How sensitive is Newton-Raphson to the initial guess compared to bisection?', 'Numerical Analysis'),
    ('What is a triage meeting and who should attend it?', 'Methodology'),
    ('How do you implement a circuit breaker pattern to prevent cascading system failures?', 'Architecture'),
    ('How does an MX record direct email to the right mail server?', 'Networking'),
    ('How does a plugin architecture let features load at runtime?', 'Architecture'),
    ("What is a linter actually catching that a compiler wouldn't?", 'Tools'),
    ('What is the difference between a compiler and an interpreter?', 'Programming'),
    ('How do you highlight the active page link in a navigation bar?', 'Web Development'),
    ('How do you choose an IDE versus a lightweight text editor for a team?', 'Tools'),
    ("What happens when a sprint's scope changes halfway through?", 'Methodology'),
    ('How do you protect a public endpoint from malicious brute-force authentication attempts?', 'Web Development'),
    ('How do foreign keys work in MySQL?', 'Database'),
    ('How does recursion actually work under the hood with the call stack?', 'Programming'),
    ('What is phase containment of defects and why is it cheaper?', 'SDLC'),
    ('How do cookies differ from sessions in a web app?', 'Web Development'),
    ('How do you choose a methodology for a client who wants fixed pricing?', 'Methodology'),
    ('What is a generic type and when would you actually need one?', 'Programming'),
    ('What is the difference between logical and physical architecture diagrams?', 'Architecture'),
    ('What is infrastructure as code (IaC) and which tools are commonly used to manage it?', 'Tools'),
    ('How do you build an infinite scroll feed instead of numbered pages?', 'Web Development'),
    ('How does the composite pattern treat single items and groups uniformly?', 'Architecture'),
    ('How do you split a story that is too big for one sprint?', 'Methodology'),
    ('How does DNS resolve a domain name to an IP address?', 'Networking'),
    ('How does an event bus differ from direct service-to-service calls?', 'Architecture'),
    ('What happens if you apply Newton-Raphson to a function with no real root?', 'Numerical Analysis'),
    ('What is the difference between stub and mock in unit testing?', 'Testing'),
    ('What is partial pivoting preventing during elimination?', 'Numerical Analysis'),
    ('How do Blade components help avoid repeating HTML across pages?', 'Web Development'),
    ('How do you structure test cases for an application that handles complex financial transactions?', 'Testing'),
    ('How does big O notation describe growth rather than raw speed?', 'Programming'),
    ('What is an issue template and how does it improve bug reports?', 'Tools'),
    ('How do you handle a stakeholder who wants Waterfall-style fixed deadlines in an Agile project?', 'Methodology'),
    ('What is the sunk cost trap in deciding whether to continue a feature?', 'Methodology'),
    ('How does a system assign unique identifiers without a central counter?', 'Architecture'),
    ('Where does a feasibility study sit in the lifecycle?', 'SDLC'),
    ('What is the difference between a state management library and a native context API?', 'Web Development'),
    ('What is the specification pattern for composable business rules?', 'Architecture'),
    ('How do you roll back a bad deployment quickly?', 'Tools'),
    ('What is the difference between standard covariance and contravariance in generic types?', 'Programming'),
    ('How do you design a system to scale horizontally instead of vertically?', 'Architecture'),
    ('How do you decide which tests to automate first on a legacy codebase?', 'Testing'),
    ('How do event-driven architectures differ from request-response ones?', 'Architecture'),
    ('What is a working agreement and what should a new team put in one?', 'Methodology'),
    ('How does the fixed-point iteration method find a root?', 'Numerical Analysis'),
    ('What is MoSCoW prioritization and how are the categories used?', 'Requirements'),
    ('How do you decide which tests run on every commit versus nightly?', 'Testing'),
    ('How do you handle requirements that change after development starts?', 'Requirements'),
    ('How does prototyping fit into the early lifecycle phases?', 'SDLC'),
    ('How do methodology choices change once a team scales past ten people?', 'Methodology'),
    ('How does a three-way handshake establish a TCP connection?', 'Networking'),
    ('What is the difference between server-side and client-side rendering?', 'Web Development'),
    ("How does read and write splitting shape a system's data access design?", 'Architecture'),
    ('What is the difference between the stabilization phase and the active development phase?', 'SDLC'),
    ('How does Crystal methodology differ from Scrum?', 'Methodology'),
    ('What is the difference between OLTP and OLAP workloads?', 'Database'),
    ('How do you recover a deleted branch in Git?', 'Tools'),
    ('How do composer scripts automate common project commands?', 'Tools'),
    ("What is the repository pattern solving that a plain query wouldn't?", 'Architecture'),
    ('How do standup formats differ between Scrum and Kanban teams?', 'Methodology'),
    ('What is a product backlog versus a sprint backlog?', 'Methodology'),
    ('How does ARP resolve an IP address to a physical address?', 'Networking'),
    ('What is the difference between a 302 redirect and rendering a view directly?', 'Web Development'),
    ('What is the difference between incremental and iterative development?', 'Methodology'),
    ('What is CQRS and when does it actually add value over a simple CRUD design?', 'Architecture'),
    ('What is a stakeholder requirement versus a solution requirement?', 'Requirements'),
    ('What is a flash message and how do you display one after a redirect?', 'Web Development'),
    ('What is the stopping criterion typically used for root-finding algorithms?', 'Numerical Analysis'),
    ('How does floating point representation cause 0.1 plus 0.2 issues?', 'Programming'),
    ('Why do some development lifecycles mandate an architectural spike before implementation?', 'SDLC'),
    ('How do you implement secure password hashing using bcrypt inside a backend framework?', 'Web Development'),
    ('How do you inspect HTTP traffic with the browser developer tools network tab?', 'Tools'),
    ('What is tail call optimization and which languages actually support it?', 'Programming'),
    ('How does the observer pattern actually get used in real applications?', 'Architecture'),
    ('How do you prioritize conflicting requirements from different stakeholders?', 'Requirements'),
    ('What is the difference between a domain model and a data model?', 'Architecture'),
    ('What is the difference between a functional and non-functional requirement?', 'Requirements'),
    ("What is the Runge-Kutta method improving over Euler's method?", 'Numerical Analysis'),
    ('What is duck typing and how does it differ from static typing?', 'Programming'),
    ('What is the difference between Git cherry-pick and Git revert?', 'Tools'),
    ('What is the difference between alpha testing and beta testing?', 'Testing'),
    ('What is ambiguity in a requirement and how do you test for it?', 'Requirements'),
    ('What is the difference between eager and lazy evaluation?', 'Programming'),
    ('How do lifecycle phases map onto a semester-long student project?', 'SDLC'),
    ('What is a deadlock and how does the database resolve one?', 'Database'),
    ('What is the difference between a defect and a failure in testing terms?', 'Testing'),
    ('Is the SDLC the same thing as a project management framework?', 'SDLC'),
    ('How does a firewall decide what traffic to block?', 'Networking'),
    ('What is an .editorconfig file and what does it standardize?', 'Tools'),
    ('Why does Newton-Raphson fail when the derivative is zero?', 'Numerical Analysis'),
    ('How do you set up automatic deployments using GitHub Actions or GitLab CI?', 'Tools'),
    ('What is the difference between a clustered and non-clustered index?', 'Database'),
    ('How does the trapezoidal rule approximate an integral?', 'Numerical Analysis'),
    ('What is a junction table and what do its keys look like?', 'Database'),
    ('What is sustainable pace and why do crunch periods backfire?', 'Methodology'),
    ('How does bitwise AND differ from logical AND?', 'Programming'),
    ('How do you keep a long-lived branch from drifting too far from main?', 'Tools'),
    ('How do you prevent double form submission when a user clicks twice?', 'Web Development'),
    ('How do you know if a project should skip straight to prototyping?', 'SDLC'),
    ('How do you run a scheduled job with cron on a server?', 'Tools'),
    ('How does TCP congestion control slow down a fast sender?', 'Networking'),
    ('How do you secure a form against CSRF attacks?', 'Web Development'),
    ('How do you resolve a complex Git merge conflict that involves binary assets?', 'Tools'),
    ("How specific should a user story's acceptance criteria be?", 'Requirements'),
    ('What is the difference between system testing and acceptance testing in the lifecycle?', 'Testing'),
    ('What is a phase gate and why do some teams enforce them strictly?', 'SDLC'),
    ('What is the CAP theorem and how does it apply to database design?', 'Database'),
    ('How do you add an SSH key so pushes stop asking for a password?', 'Tools'),
    ('How does Extreme Programming handle code ownership and architectural decisions?', 'Methodology'),
    ('What is the difference between inline, internal, and external CSS?', 'Web Development'),
    ('How do you organize arrange, act, and assert in a readable test?', 'Testing'),
    ('What is the flyweight pattern and what memory problem does it solve?', 'Architecture'),
    ('What makes a requirement testable versus vague?', 'Requirements'),
    ('How do you test error paths that are hard to trigger naturally?', 'Testing'),
    ('What is regression testing and when should it run?', 'Testing'),
    ('What is the purpose of Git reflog and how can it save lost commits?', 'Tools'),
    ('What is the difference between a cookie and local storage?', 'Web Development'),
    ('What is the difference between a proxy and a VPN?', 'Networking'),
    ('What is an end to end test covering that integration tests skip?', 'Testing'),
    ('How does a spiral model differ from a standard linear SDLC?', 'SDLC'),
    ('How do you write an acceptance test from a single user story?', 'Requirements'),
    ('What is slack time in a sprint and why leave any?', 'Methodology'),
]